### ISSUE TITLE
gson concurrent problems if I have static hashMap

### ISSUE THREAD

**Issue by LinoOscar** [google/gson#1040]
Hi friends!

Thanks for your work! I will going to open this issue, but it is the typical problem that is in the frontier of products, and is the fault of one or another according to the eyes that you are using for study it :-)

This is my stack trace:

java.util.ConcurrentModificationException
	at java.util.HashMap$AbstractMapIterator.checkConcurrentMod(HashMap.java:197)
	at java.util.HashMap$AbstractMapIterator.makeNext(HashMap.java:202)
	at java.util.HashMap$EntryIterator.next(HashMap.java:263)
	at java.util.HashMap$EntryIterator.next(HashMap.java:256)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:206)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at es.isban.portlets.util.JSONUtils.toJson(JSONUtils.java:41)

I review your code and i discover that the problem is that you are using one iterator over the same map that i am sending to you.... and I obtain one problem in your code due that there are more than one thread over my Hashmap

Obsiously, if i use concurrentHashMap or hastTable I avoid the problem but... really you aren't thread-safe in this case, at least, theorically...

So, i open this issue only for inform you... are this one bug, maybe must you clone income map for avoid problems? Who knows!!!

Thanks for your great product!!

Regards,
Lino

**Comment by JakeWharton** [comment]
What would you expect Gson to do in this case? Even if we try and make a
defensive copy (which would be crazy slow), it still uses an Iterator to
copy the data.

**Comment by LinoOscar** [comment]
Hi Jake

I'm agree with you that any change in this case is unacceptable in performance terms; i will change my code, but I have considered important collaborate in your great work; if anyone in the future have this problem, he will be able to read this thread and discover that the same instance map  of this code is the printted map, and he must solved in own code concurrent problem.
