### ISSUE TITLE
java.util.ConcurrentModificationException         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)

### ISSUE THREAD

**Issue by mrudangit** [google/gson#1061]
Getting java.util.ConcurrentModificationException from time to time. 

I had multiple threads doing :+1: 

  String json = objectToJSON.toJson(payload);

payload is HashMap<String,Object>

Object in the HashMap is simple 

Object of type is this class
public class PriceLevel {

    private double px;
    @Expose private long bs;
    @Expose private long as;

    @Override
    public String toString() {
        return "PriceLevel{" +
                "px=" + px +
                ", bs=" + bs +
                ", as=" + as +
                '}';
    }

    public PriceLevel(double price, long bidSize, long askSize){
        this.px = price;
        this.bs = bidSize;
        this.as = askSize;
    }

    public String getDecimalPx(){
        return  BigDecimal.valueOf(px).setScale(10,BigDecimal.ROUND_HALF_EVEN).stripTrailingZeros().toPlainString();
    }

    public Double getPx() {
        return px;
    }

    public void setPx(Double px){
        this.px = px;
    }

    public long getBs() {
        return bs;
    }

    public void setBs(long bs) {
        this.bs = bs;
    }

    public long getAs() {
        return as;
    }

    public void setAs(long as) {
        this.as = as;
    }

}

I even made the method doing   String json = objectToJSON.toJson(payload);  synchronized

still i get the exception 

java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:206)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.toJson(Gson.java:669)
        at com.google.gson.Gson.toJson(Gson.java:648)
        at com.google.gson.Gson.toJson(Gson.java:603)
        at com.google.gson.Gson.toJson(Gson.java:583)

**Comment by inder123** [comment]
Please write it as a JUnit test that reproduces the problem. Thanks.
