### ISSUE TITLE
NullPointerException on toJsonTree()

### ISSUE THREAD

**Issue by gauravtyagi77** [google/gson#1077]
Hi,

I am getting below error but not every time it comes once in a month while running. Not able to reach exact root cause so please help.

2017-05-08 08:51:02,228 ERROR [pool-36-thread-5] c.n.f.t.p.t.m.FormattedMessage [FormattedMessage.java:252] Message generation in formatted message class -->java.lang.NullPointerException
	at com.google.gson.Gson.getAdapter(Gson.java:353)
	at com.google.gson.Gson.toJson(Gson.java:578)
	at com.google.gson.Gson.toJsonTree(Gson.java:479)
	at com.google.gson.Gson.toJsonTree(Gson.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Library version i am using is gson-2.2.2 .

**Comment by egor-n** [comment]
Gson 2.2.2 has been released [5 years ago](https://github.com/google/gson/releases/tag/gson-2.2.2). Can you reproduce the issue on the latest version?

**Comment by gauravtyagi77** [comment]
I know it's an old version but I am unable to change it as it is in my production environment on which this issue is coming and can not change version in production . I need to know if this was issue in existing version and changed in newer versions than I may try.

**Comment by gauravtyagi77** [comment]
Thanks for such and immediate response.

**Comment by vickysimple** [comment]
I saw the same behavior on 2.1 only once in 5000 attempts and I can not reproduce it. Yes I can upgrade it but I am not if this is problem with my application or GSON. Does anyone know the root cause for this?

**Comment by gauravtyagi77** [comment]
If we initialize GSON object in multi threading environment then this exception occurs randomly. Please use below code in synchronized manner.
GsonBuilder gsonBuilder = new GsonBuilder();
Gson gson = gsonBuilder.create();

**Comment by vickysimple** [comment]
I have a static gson builder from which every thread creates its Gson object. Did you have a similar setup? It has failed only twice for me and I can reproduce it. Which makes it even more hard to debug.
