### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Myeongwon-Kang** [google/gson#1089]
Error while using gson 2.8.

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/internal/
       at com.google.gso.<clinit>(TypeAdapters.java:426)
       at com.google.gson.Gson.<init>(Gson.java:199)
       at com.google.gson.GsonBuilder.create(GsonBuilder.java:569)

device : Galaxy Note5

**Comment by JakeWharton** [comment]
This is either a problem with your packaging of the APK or a problem with
the OS on the device. There's no action to take on our part.
