### ISSUE TITLE
call new GsonBuilder().setDateFormat("yyyy-MM-dd").create().toJson exception.[2.8.1]

### ISSUE THREAD

**Issue by yuli13244** [google/gson#1145]
when a pojo object with null-value field and use "GsonBuilder().setDateFormat("yyyy-MM-dd")",will throw exception.

code:
//data class
class Person{
  private Date age;
  //getter setter
}

//demo
Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd").create();
Person p = new Person(); //age is null
System.out.println(gson.toJson(p));

//exception
Exception in thread "main" java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:88)
	at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:40)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)

**Comment by yuli13244** [comment]
@lyubomyr-shaydariv  I get it , thank you.
