### ISSUE TITLE
Getting this issue while using GSON Api

### ISSUE THREAD

**Issue by MM00360815** [google/gson#1197]
S:Fault 	xmlns:ns4="http://www.w3.org/2003/05/soap-envelope">
<faultcode>S:Server</faultcode>
<faultstring>
EJB Exception: : java.lang.StackOverflowError
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
 at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)

**Comment by NightlyNexus** [comment]
#1128 fixes this. Use Gson 2.8.2.
