### ISSUE TITLE
Double.NaN as JsonObject property generates invalid JSON and does not throw exception

### ISSUE THREAD

**Issue by danorton2** [google/gson#1203]
Code fragment:
```java
    final Gson gson = new GsonBuilder().serializeNulls().create();
    JsonObject jsonObject = new JsonObject();
    jsonObject.addProperty("invalidDouble", Double.NaN);
    JsonElement jsonElement = jsonObject;
    log("As property within object: " + jsonElement.toString()); // expect this to throw exception
    jsonElement = gson.toJsonTree(Double.NaN);
    log("As primitive: " + jsonElement.toString());  // this throws exception, as expected
```
Output:
```
As property within object: {"invalidDouble":NaN}
Exception in thread "main" java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
	at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:324)
	at com.google.gson.Gson$1.write(Gson.java:292)
	at com.google.gson.Gson$1.write(Gson.java:278)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJsonTree(Gson.java:562)
	at com.google.gson.Gson.toJsonTree(Gson.java:541)
```

**Comment by danorton2** [comment]
Related:
- #81
- #498

**Comment by danorton2** [comment]
Similar to #752 - Special FP values serialized without error when using JsonPrimitive (when this option is disabled)

**Comment by danorton2** [comment]
Like #752, this does not thrown an exception:
```java
    jsonElement = new JsonPrimitive(Double.NaN);
    log("As primitive: " + jsonElement.toString());  // expect this to throw exception
```

**Comment by danorton2** [comment]
Is this a result of this PR?
- #1093 - value(double) can write NaN and infinite values when lenient, as value(Number) does

**Comment by danorton2** [comment]
See also:
- #372 - GsonBuilder.setLenient(false)

**Comment by Marcono1234** [comment]
The problem here is that the non-finite floating point value check, which is affected by `GsonBuilder.serializeSpecialFloatingPointValues()`, only occurs for `Float` and `Double` (and the corresponding primitive types). However, any other adapter which directly uses `JsonWriter.value(Number)` (such as the adapter for `JsonElement`) is not influenced by this, and is only affected by the lenientness of the `JsonWriter`. And as mentioned in #372 (and related issues) that writer is unfortunately lenient by default.
