### ISSUE TITLE
com.google.gson.stream.JsonWriter.beforeValue(JsonWriter.java:642) java.lang.stackoverflowerror

### ISSUE THREAD

**Issue by august1** [google/gson#1261]
I use gson 2.8.0，
Now this is not a problem. but this problem appears occasionally.
who can help me, thank you very much.
detail error message:
jva.lang.StackOverflowErroava.lang.StackOverflowError
        at com.google.gson.stream.JsonWriter.beforeValue(JsonWriter.java:642)
        at com.google.gson.stream.JsonWriter.open(JsonWriter.java:325)
        at com.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:308)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:238)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)

now this problem

**Comment by Marcono1234** [comment]
Is this still relevant? If so could you please try the latest Gson version and provide a small self-contained example showing this issue?

It looks like there might be a cycle in the object graph you are serializing.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
