### ISSUE TITLE
NullPointerException during parsing object

### ISSUE THREAD

**Issue by imakhalova** [google/gson#1298]
I'm getting some blob from network and trying to parse it. Like that:
Gson gson = new Gson();
            if (!TextUtils.isEmpty(header)) {
                JWSHeader jwsHeader = gson.fromJson(header, JWSHeader.class);
            }

Most of the time it works well, but for some users it crashes. My guess is that data was corrupted ( I don't have sample of corrupted data). But shouldn't gson handle gracefully any wrong data and return null object instead?

Stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
              at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
              at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:74)
              at com.google.gson.reflect.TypeToken.get(TypeToken.java:296)
              at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
              at com.google.gson.Gson.getAdapter(Gson.java:423)
              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
              at com.google.gson.Gson.getAdapter(Gson.java:423)
              at com.google.gson.Gson.fromJson(Gson.java:886)
              at com.google.gson.Gson.fromJson(Gson.java:852)
              at com.google.gson.Gson.fromJson(Gson.java:801)
              at com.google.gson.Gson.fromJson(Gson.java:773)

**Comment by inder123** [comment]
@imakhalova possibly... would love a specific proposal with a PR

**Comment by bhuvnesh123** [comment]
@inder123 @imakhalova What does it mean by top-level String is null?I tried to get above exception by using- `new Gson().fromJson("{null: null}", XYZ.class)`..But still i am not getting this exception

**Comment by bhuvnesh123** [comment]
@inder123 @imakhalova Can you give example of corrupt json which can cause above exception?If below is the sample json which is send inside fromJson() and which works fine,then what possible change I can make to this so that it generates above exception?The exception logs doesn't explain what is making it corrupt..and i just want to recreate the exception so that i can get an idea that which key or value is getting corrupt.
{"A":{"B":0.0,"C":1542198709727,"D":0.0}}

**Comment by lyubomyr-shaydariv** [comment]
@bhuvnesh123 
I don't really think it's a Gson-related issue, and I believe it has nothing to do with probably corrupted JSON documents: according to the exception, [here](https://android.googlesource.com/platform/libcore/+/5d930ca/luni/src/main/java/libcore/reflect/TypeVariableImpl.java#47), it may be thrown:

* either at `getName().hashCode()`
* or at `getGenericDeclaration().hashCode()`

I guess, that something causes the `Type` instance to get into a wrong state, and I guess something gets erased (let's say with Proguarding (similar [example](https://github.com/orhanobut/hawk/issues/143)); not sure how it deals with "some users" though). Make sure your type passed to `fromJson` and whatever types that might play in deserialization are well-wormed.

**Comment by lll-01** [comment]
```
java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
1 libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
2 java.util.HashMap.hash(HashMap.java:338)
3 java.util.HashMap.containsKey(HashMap.java:595)
4 java.util.HashSet.contains(HashSet.java:203)
5 com.google.gson.internal.$Gson$Types.resolve(Unknown Source:16)
6 com.google.gson.internal.$Gson$Types.resolve(Unknown Source:188)
7 com.google.gson.internal.$Gson$Types.resolve(Unknown Source:5)
8 com.google.gson.internal.$Gson$Types.getSupertype(Unknown Source:24)
9 com.google.gson.internal.$Gson$Types.getCollectionElementType(Unknown Source:3)
10 com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(Unknown Source:18)
11 com.google.gson.Gson.getDelegateAdapter(Unknown Source:35)
12 com.eom.utils.gson.TypeSafeAdapterFactory.create(Unknown Source:32)
13 com.google.gson.Gson.getAdapter(Unknown Source:75)
14 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(Unknown Source:38)
15 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(Unknown Source:117)
16 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(Unknown Source:22)
17 com.google.gson.Gson.getDelegateAdapter(Unknown Source:35)
18 com.eom.utils.gson.TypeSafeAdapterFactory.create(Unknown Source:162)
19 com.google.gson.Gson.getAdapter(Unknown Source:75)
20 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(Unknown Source:38)
21 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(Unknown Source:117)
22 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(Unknown Source:22)
23 com.google.gson.Gson.getDelegateAdapter(Unknown Source:35)
24 com.eom.utils.gson.TypeSafeAdapterFactory.create(Unknown Source:162)
25 com.google.gson.Gson.getAdapter(Unknown Source:75)
26 com.google.gson.Gson.fromJson(Unknown Source:17)
27 com.google.gson.Gson.fromJson(Unknown Source:4)
28 com.google.gson.Gson.fromJson(Unknown Source:9)
```

**Comment by kashu1209** [comment]
Please provide a solution to this exception if the issue is resolved or Reopen it please.

**Comment by akkuprin** [comment]
same problem for some users

**Comment by zewenwang** [comment]
@lll-01  Has this problem been resolved? It happens to me on version Gson 2.8.5

**Comment by EmMper** [comment]
I got this problem too.

I'm sure that top-level String is not null, and data was not corrupted.I just want to get an object from a specific json file which would not be changed.

This problem occurred occasionally. Is there any solutions or suggestions?
@inder123

**Comment by GokuSa** [comment]
I got the same problem too. It happens to me on version Gson 2.90

**Comment by FaisalThreestops** [comment]
I can't able to convert json to my model class

String result = "{\"data\":{\"userid\":\"61de9b0373ea9163554e2a9f\",\"firstName\":\"new\",\"lastName\":\"user\",\"email\":\"test@gmail.com\",\"channelid\":\"61b75e1b8cda97bf44f3af40\",\"isActive\":true},\"status\":200}";
        Gson gson1 = new Gson();
        ProfileResponse responses = gson1.fromJson(result, ProfileResponse.class);
        Log.d("dooth-faisal","sucess:"+responses.getData().getFirstName());
        
I have using below depandancy
 gsonVersion = '2.8.2'
dagger2Version = '2.16'
    rxjava2Version = '2.1.9'
    rxandroidVersion = '2.0.2'
  retrofit_version = '2.9.0'
    retrofit_rxjava_version = '1.0.0'
    //dependency here..
implementation 'io.github.inflationx:calligraphy3:3.1.1'
    implementation 'io.github.inflationx:viewpump:2.0.3'

    implementation 'com.jakewharton:butterknife:10.2.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.3'

    // dependency injection
    implementation "com.google.dagger:dagger:$rootProject.dagger2Version"
    annotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"
    compileOnly 'javax.annotation:jsr250-api:1.0'
    implementation 'javax.inject:javax.inject:1'

    // reactive
    implementation "io.reactivex.rxjava2:rxjava:$rootProject.rxjava2Version"
    implementation "io.reactivex.rxjava2:rxandroid:$rootProject.rxandroidVersion"


    /* Retrofit using  Okhttp, Okhttp logging interceptor, Gson  */
    // Retrofit
    //implementation "com.squareup.retrofit2:retrofit:$rootProject.retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$rootProject.gsonVersion"
    implementation "com.jakewharton.retrofit:retrofit2-rxjava2-adapter:$rootProject.retrofit_rxjava_version"
    implementation("com.squareup.retrofit2:retrofit:$rootProject.retrofit_version")
            {
                exclude module: 'okhttp'
            }

error shown
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.cha/.ProfileActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException

**Comment by eamonnmcmanus** [comment]
The latest Gson version is 2.8.9. Does your problem still show up with that?

We would need to see more of the stack trace. There are no Gson frames in what's shown. What shows up after `Caused by: java.lang.NullPointerException`?

**Comment by Marcono1234** [comment]
@b1tb1t, could you please test if you are still experiencing this with the latest Gson version (currently 2.10)?
Please also have a look at the discussion in #1778. Are you able to create a small self-contained example which allows reproducing this issue?

**Comment by VEZE** [comment]
We are using 2.13.1 and still experiencing same issue.
