### ISSUE TITLE
Enhancement: Include unparsable string in JsonSyntaxException

### ISSUE THREAD

**Issue by tomasbjerre** [google/gson#1299]
# Problem

I often see stacktraces like the one reported here: https://github.com/jenkinsci/violation-comments-to-github-plugin/issues/14
```
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 10
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
	... 25 more
```

In this case this is most likely caused by some proxy that intercepts an invocation and responds with none JSON. But that is not clear from the error and the reporter opens an issue in my project regarding this.

## Workaround
When possible, I catch the exception and throw a new one containing the String that could not be parsed.

But that is not possible when this happens in a 3rd party dependency like this. I also think it would better to throw a clear exception here in Gson so that there is no need to wrap it.

# Proposed solution

Include the unparsable JSON in the thrown exception. Perhaps make it configurable so that people can avoid logging secrets.

**Comment by lyubomyr-shaydariv** [comment]
```java
gson.fromJson("         <html>", Map.class);
```

The above would produce `path $`, and single `$`  usually indicates an illegal JSON object (occurs when accessing secured resources that produce HTML documents as HTTP 403, exactly the same as you mentioned).

As far as I understand how Gson `JsonReader` works, it only consumes an internal buffer filled up from the `Reader` (1K?) to determine the next JSON token by character not reading entire string, and exposing the current buffer state is probably not a good idea as well as reading the next token entirely (strings can be expensive to collect/read and concatenate/propagate via exception messages; buffer current position can be close to the very end of the buffer therefore emitting a very short string if not reading the next data to the buffer; reading the next data may fail; etc).

A possible work-around for your Gson version:

```java
final class TrackingReader
		extends Reader {

	private final Reader reader;

	private char[] buffer;

	TrackingReader(final Reader reader) {
		this.reader = reader;
	}

	@Override
	public int read(@NotNull final char[] buffer, final int offset, final int length)
			throws IOException {
		final int read = reader.read(buffer, offset, length);
		this.buffer = new char[read];
		System.arraycopy(buffer, offset, this.buffer, 0, read);
		return read;
	}

	@Override
	public void close()
			throws IOException {
		reader.close();
	}

	String getBufferAsString() {
		return new String(buffer);
	}

}
```

```java
final class TrackingJsonReader
		extends JsonReader {

	private final TrackingReader trackingReader;

	private TrackingJsonReader(final TrackingReader trackingReader) {
		super(trackingReader);
		this.trackingReader = trackingReader;
	}

	static JsonReader get(final TrackingReader trackingReader) {
		return new TrackingJsonReader(trackingReader);
	}

	@Override
	public void beginObject()
			throws IOException {
		try {
			super.beginObject();
		} catch ( final IllegalStateException ex ) {
			if ( isRoot() ) {
				throw new IllegalArgumentException(readStatus());
			}
			throw ex;
		}
	}

	private boolean isRoot() {
		return getPath().equals("$");
	}

	private String readStatus()
			throws IOException {
		final Appendable builder = new StringBuilder();
		builder.append("VALUE: `");
		switch ( peek() ) {
		case STRING:
			// Reading the next string may be too expensive, but we are fine with it here
			builder.append(nextString());
			break;
		default:
			throw new UnsupportedOperationException("TODO");
		}
		builder.append("`  BUFFER: `");
		builder.append(trackingReader.getBufferAsString());
		builder.append("`");
		return builder.toString();
	}

}
```

Example of use:

```java
final Gson gson = new Gson();
final Reader reader = new StringReader("         <html><title></title></html>");
final TrackingReader trackingReader = new TrackingReader(reader);
final JsonReader jsonReader = TrackingJsonReader.get(trackingReader);
gson.fromJson(jsonReader, Map.class);
```

```
 java.lang.IllegalArgumentException: VALUE: `<html><title><`  BUFFER: `         <html><title></title></html>`
```

**Comment by tomasbjerre** [comment]
There is no need to discuss older versions here. I'm totally fine with this being added to new releases.

At least, these methods:
```
  public <T> T fromJson(String json, Class<T> classOfT) throws JsonSyntaxException {
    Object object = fromJson(json, (Type) classOfT);
    return Primitives.wrap(classOfT).cast(object);
  }
```

And:
```
  public <T> T fromJson(String json, Type typeOfT) throws JsonSyntaxException {
    if (json == null) {
      return null;
    }
    StringReader reader = new StringReader(json);
    T target = (T) fromJson(reader, typeOfT);
    return target;
  }
```

Can easily be fixed with something like:
```
try {
 the current implementation...
} catch (JsonSyntaxException e) {
 throw new JsonSyntaxException("Unable to parse: "+json,e);
}
```

**Comment by lyubomyr-shaydariv** [comment]
Unfortunately, this can only work for strings at the very top level, and won't work for streams like `JsonReader`. What if you just wrap your `Gson.fromJson` like this:

```java
final Gson gson = new Gson();
final Reader reader = new StringReader("         <html><title></title></html>");
final Reader accumulatingReader = new Reader() {
	private final StringBuilder accumulator = new StringBuilder();

	@Override
	public int read(final char[] buffer, final int offset, final int length)
			throws IOException {
		final int read = reader.read(buffer, offset, length);
		accumulator.append(buffer, offset, read);
		return read;
	}

	@Override
	public void close()
			throws IOException {
		reader.close();
	}

	@Override
	public String toString() {
		return accumulator.toString();
	}
};
final JsonReader jsonReader = new JsonReader(accumulatingReader);
try {
	gson.fromJson(jsonReader, Map.class);
} catch ( final JsonSyntaxException ex ) {
	throw new JsonSyntaxException("Cannot parse: " + accumulatingReader, ex);
}
```

? Such an approach can apply any strategies and is able to work with any deserialization libraries.

**Comment by tomasbjerre** [comment]
Yes, it can be wrapped by the using code. I mentioned that in my first post.

But users don't generally do that. If this information is in the original exception, then the problem is eliminated.

**Comment by Marcono1234** [comment]
One issue might be that this could leak sensitive information, depending on how the exception is handled. So in case this is implemented it might make sense to make this an opt-in method of `JsonReader`?
