### ISSUE TITLE
No direct method <init>(Lcom/google/gson/Gson;)V in class Lcom/google/gson/Gson$1; or its super classes 

### ISSUE THREAD

**Issue by shyakdas** [google/gson#1358]
Crashing in Huawei, Samsung

**Comment by samsax** [comment]
I have the same error in test production apk
`FATAL EXCEPTION: AsyncTask #2
Process: taxiplus.passenger, PID: 14524
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:330)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/gson/Gson;)V in class Lcom/google/gson/Gson$1; or its super classes (declaration of 'com.google.gson.Gson$1' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)
	at com.google.gson.Gson.doubleAdapter(Gson.java:313)
	at com.google.gson.Gson.<init>(Gson.java:242)
	at com.google.gson.Gson.<init>(Gson.java:186)
	at myapp.passenger.SplashActivity1$BackgroundTaskGetAboutUs.doInBackground(SplashActivity1.java:127)
	at myapp.passenger.SplashActivity1$BackgroundTaskGetAboutUs.doInBackground(SplashActivity1.java:81)
	at android.os.AsyncTask$2.call(AsyncTask.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more`

**Comment by nambv** [comment]
Yes, I got them same crash in Huawei and Samsung too:

```
Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/gson/Gson;)V in class Lcom/google/gson/Gson$1; or its super classes (declaration of 'com.google.gson.Gson$1'
```

**Comment by Arumenn** [comment]
Same as #1354
