### ISSUE TITLE
com.google.gson.LruCache causing stuck thread with com.google.code.gson version 1.5

### ISSUE THREAD

**Issue by parthapratimpradhan** [google/gson#1383]
Version:
<groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>1.5</version>
Issue details:
[STUCK] ExecuteThread: '355' for queue: 'weblogic.kernel.Default (self-tuning)'" daemon prio=10 tid=0x00007f128c081800 nid=0xd95 runnable [0x00007f11eecaa000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.getEntry(HashMap.java:469)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:301)
	at com.google.gson.LruCache.getElement(LruCache.java:49)
	at com.google.gson.FieldAttributes.getAnnotations(FieldAttributes.java:150)
	at com.google.gson.FieldAttributes.getAnnotation(FieldAttributes.java:138)
	at com.google.gson.SerializedNameAnnotationInterceptingNamingPolicy.translateName(SerializedNameAnnotationInterceptingNamingPolicy.java:44)
	at com.google.gson.JsonObjectDeserializationVisitor.getFieldName(JsonObjectDeserializationVisitor.java:92)
	at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:97)
	at com.google.gson.ObjectNavigator.navigateClassFields(ObjectNavigator.java:158)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:131)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:73)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:495)
	at com.google.gson.Gson.fromJson(Gson.java:444)
	at com.google.gson.Gson.fromJson(Gson.java:396)
	at com.google.gson.Gson.fromJson(Gson.java:372)

**Comment by JakeWharton** [comment]
This version of Gson is no longer supported. We only work on the 2.x version.

**Comment by parthapratimpradhan** [comment]
Hi can you please at least confirm that in the latest version of com.google.code.gson we are not using Lru cache which was the primary cause of the issue?

**Comment by JakeWharton** [comment]
LruCache doesn't exist anymore, yes.
