### ISSUE TITLE
Deserisation fails with null numeric primitive keys

### ISSUE THREAD

**Issue by AudriusButkevicius** [google/gson#1385]
**What did you do:**

Ran:
```
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.HashMap;
import java.util.Map;

public class Test {
    static class MyType {
        public Map<Integer, Integer> map = new HashMap<>();
    }

    public static void main(String[] args) {
        MyType instance = new MyType();
        instance.map.put(null, 1);

        Gson serialiser = new GsonBuilder()
                .enableComplexMapKeySerialization()
                .serializeNulls()
                .setPrettyPrinting()
                .create();

        String data = serialiser.toJson(instance);
        System.out.println(data);

        try {
            MyType newInstance = serialiser.fromJson(data, MyType.class);
            System.out.println("Success");
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }
}
```

**What happened**

Deserialisation fails:

```
{
  "map": {
    "null": 1
  }
}
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "null"
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at Test.main(Test.java:27)
Caused by: java.lang.NumberFormatException: For input string: "null"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
	... 11 more
```

**What did you expect to happen:**

Deserialisation to succeed, and "Success" message to be printed

_Note_

Strangely it works ok if you serialise a simple map (not embedded in an object).

**Comment by AudriusButkevicius** [comment]
This issue is not really a question, I understand loud and clear what's happening. I am asserting that the behaviour is incorrect and that this should be fixed.

I do expect it to convert the keys to integers, I also expect it to eat it's own dog food and be able to deserialise a value it produced on serilisation.


The library should either refuse to serialise null primitive keys (as it cannot deserialise them), or be fixed to deserialise the values it produced when serialising.

It (the test) works ok when using a map that is not embedded in an object, and fails when map is embedded in an object, which further shows inconsistencies in the behaviour, implying an issue.

**Comment by AudriusButkevicius** [comment]
What exactly would you be breaking? Preventing null key serialisation? What about deserialising "null" strings into nulls for boxed primitives (other than string I guess)

**Comment by yanxinyuan** [comment]
I also think it is an issue, here is the code: 

Scenario 1: 
```
Gson gson = new GsonBuilder().serializeNulls().create();
Map<String, Integer> mapData = new HashMap<>();
mapData.put("abc", null);
String data = gson.toJson(mapData);
System.out.println(data);
Type type = TypeToken.getParameterized(HashMap.class, String.class, Integer.class).getType();
Object obj = gson.fromJson(data, type);
System.out.println(obj);
```
The code runs well and got the result
```
{"abc":null}
{abc=null}
```
Scenario 2:
```
Gson gson = new GsonBuilder().serializeNulls().create();
Map<Integer, String> mapData = new HashMap<>();
mapData.put(null, "abc");
String data = gson.toJson(mapData);
System.out.println(data);
Type type = TypeToken.getParameterized(HashMap.class, Integer.class, String.class).getType();
Object obj = gson.fromJson(data, type);
System.out.println(obj);
```
The  code runs failed, and get an exception:
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "null"
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.delta.cornerstone.common.serialization.gson.user.UserSerializationByGson.main(UserSerializationByGson.java:41)
Caused by: java.lang.NumberFormatException: For input string: "null"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225)
	... 8 more
```

So it seems Gson can only handle the "NULL" when it is the value of the map.
