### ISSUE TITLE
class declares multiple JSON fields - How to tell Gson to consider child class field.

### ISSUE THREAD

**Issue by Padmahas** [google/gson#1420]
Hello,

We are using [Google Ad Manager axis API](https://github.com/googleads/googleads-java-lib) in our project. While converting [LineItem](https://developers.google.com/ad-manager/api/reference/v201808/LineItemService.LineItem) object, we are getting the below error.
```
java.lang.IllegalArgumentException: class com.google.api.ads.admanager.axis.v201808.CustomCriteriaSet declares multiple JSON fields named __equalsCalc
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:170) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[gson-2.8.0.jar:?]
```
As mentioned in [this issue](https://github.com/googleads/googleads-java-lib/issues/135), using exclusion strategy will make those fields to be null. Since those fields are mandatory, if it's sent to Ad manager we will get exception.

Hence I'm look for a way to tell Gson, instead of completely excluding the field from Deserialization, how to force Gson to consider child class fields and child class setter methods?

When it's common for a field to override it's parent class field, why not Gson consider child class's field by default? How can I overcome this exception?

Thank you.

**Comment by Padmahas** [comment]
If I exclude a field only if it is declared in parent class, as described in [this SO answer](https://stackoverflow.com/questions/16476513/class-a-declares-multiple-json-fields#answer-20117863), 

I'm still getting the multiple fields error. If I blindly exclude all "__equalsCalc" and "__hashCodeCalc" irrespective of whether it's declared in parent or not, then only I'm not getting any error. But still it will make those fields null. 

Either way, somehow I need to tell Gson to consider child class field. How to achieve that.

Thank  you.

**Comment by cedric05** [comment]
any update??

**Comment by Padmahas** [comment]
Yeah.
I excluded all "__equalsCalc" and "__hashCodeCalc", irrespective of whether it is parent or child class.
Then I had to provide custom Deserialization for all classes which throws this error.

Thank you.

**Comment by harezmi1907** [comment]
I was on a project to retire all the other JSON libraries and use GSON instead. I kept getting this error and had to leave some as they were. I don't want to use the exclusion strategy, either because there are many fields need to be excluded.
