### ISSUE TITLE
Exclusion strategy not working- getting class declares multiple JSON fields exception

### ISSUE THREAD

**Issue by Padmahas** [google/gson#1421]
Hello,

We are using [Google ad manager API](https://github.com/googleads/googleads-java-lib). I'm pretty sure that, in the previous versions of the API, the exclusion strategy, which was suggested in [this post](https://stackoverflow.com/questions/16476513/class-a-declares-multiple-json-fields#answer-20117863) was working without errors.

But in the version v201808 API, this strategy is not working. There are two ways to exclude a field from Deserialization.
1. Excluding a field from deserialization if the same field exist in the Parent class.
2. [Excluding all fields irrespective of whether they are declared in Parent class or not](https://github.com/googleads/googleads-java-lib/issues/135#issuecomment-375321658).

Both of the ways giving out the below error.

```
java.lang.IllegalArgumentException: class com.google.api.ads.admanager.axis.v201808.CustomCriteriaSet declares multiple JSON fields named __equalsCalc
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:170) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:886) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
```

Can anyone point our why exclusion strategy is not taking effect?

Thank you.

**Comment by Marcono1234** [comment]
In case this is still relevant, could you please try this with the latest Gson version and show the code for your `ExclusionStrategy` and how you create your `Gson` instance?
When registering the exclusion strategy you have to call both `addDeserializationExclusionStrategy` and `addSerializationExclusionStrategy`.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
