### ISSUE TITLE
Android studio 3.4版本问题

### ISSUE THREAD

**Issue by yindalei00** [google/gson#1523]
在 最新版 Android studio 3.4 时  使用 推荐的 gradle:3.4.0  
如果 开启 混淆( minifyEnabled true) 那么
 在使用 Gson 时  调用此方法 错误,但是 以前版本gradle 无此问题

    private <T> Map<String, T> parse(String json) {
        Map<String, T> map = null;
        try {
            map = new GsonBuilder().create().fromJson(json, new TypeToken<Map<String, T>>() {
            }.getType());
        } catch (JsonSyntaxException e) {
            e.printStackTrace();
        }
        return map;
        
    }

尝试 修改泛型 为 Object  无问题

Error info:

java.lang.AssertionError: illegal type variable reference  
	at libcore.reflect.TypeVariableImpl.resolve(TypeVariableImpl.java:111)  
	at libcore.reflect.TypeVariableImpl.getGenericDeclaration(TypeVariableImpl.java:125)  
	at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)  
	at java.util.Arrays.hashCode(Arrays.java:4074)  
	at Tb$b.hashCode($Gson$Types.java:502)  
	at Md.<init>(TypeToken.java:64)  
	at Pa.<init>(Unknown Source:0)  
	at Qa.a(Unknown Source:8)  
	at ------------hide------------.onViewClicked(RegActivity.java:182)  
	at ja.a(RegActivity_ViewBinding.java:67)  
	at I.onClick(DebouncingOnClickListener.java:18)  
	at android.view.View.performClick(View.java:6266)  
	at android.view.View$PerformClick.run(View.java:24730)  
	at android.os.Handler.handleCallback(Handler.java:793)  
	at android.os.Handler.dispatchMessage(Handler.java:98)  
	at android.os.Looper.loop(Looper.java:176)  
	at android.app.ActivityThread.main(ActivityThread.java:6701)  
	at java.lang.reflect.Method.invoke(Native Method)  
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)  
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by QuincySx** [comment]
可能是 Android Studio 3.4 默认开启 R8 导致的。可以尝试标记 gradle.properties 关闭 R8

# Disables R8 for Android Library modules only.
android.enableR8.libraries = false
# Disables R8 for all modules.
android.enableR8 = false

**Comment by yindalei00** [comment]
> 可能是Android Studio 3.4默认开启R8导致的。可以尝试编辑gradle.properties关闭R8
> 
> ```
> # Disables R8 for Android Library modules only.
> android.enableR8.libraries = false
> # Disables R8 for all modules.
> android.enableR8 = false
> ```

谢谢,关闭R8 的确 可以解决了这个问题,

**Comment by YuanKJ-** [comment]
淡腾了，遇到同样的问题，关闭R8重新运行好像也不生效，依然爆这个异常

**Comment by yindalei00** [comment]
> 淡腾了，遇到同样的问题，关闭R8重新运行好像也不生效，依然爆这个异常

我是改成Object 了,   
 同时还存在一个问题  内部静态类 也会报错

**Comment by YuanKJ-** [comment]
> > 淡腾了，遇到同样的问题，关闭R8重新运行好像也不生效，依然爆这个异常
> 
> 我是改成Object 了,
> 同时还存在一个问题 内部静态类 也会报错

是的，我也是把T类型去掉了，毕竟即使传了T类型，也解析不到正确的类型，还是需要转换一次

**Comment by yindalei00** [comment]
> > > 淡腾了，遇到同样的问题，关闭R8重新运行好像也不生效，依然爆这个异常
> > 
> > 
> > 我是改成Object 了,
> > 同时还存在一个问题 内部静态类 也会报错
> 
> 是的，我也是把T类型去掉了，毕竟即使传了T类型，也解析不到正确的类型，还是需要转换一次


找到原因了,应该 是 gson 混淆配置 问题 

有一句 ------------->  Prevent R8 from leaving Data object members always null
[https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg](url)
