### ISSUE TITLE
infinite recursion of adapters

### ISSUE THREAD

**Issue by igoryan17** [google/gson#1643]
I use 2.8.6 version. And firstly i created custom adapters and get StackOverflowError. Then i commented all my custom adapters in GsonBuilder and got following stack trace:
`java.lang.StackOverflowError
	at java.io.StringWriter.append(StringWriter.java:143)
	at java.io.StringWriter.append(StringWriter.java:41)
	at com.google.gson.stream.JsonWriter.beforeValue(JsonWriter.java:650)
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417)
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.write(TypeAdapters.java:804)
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.write(TypeAdapters.java:773)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
`
I'm stupid or it's bug?

**Comment by igoryan17** [comment]
The reason that i try serialise class with circular reference.
class A {
A a;
}

**Comment by igoryan17** [comment]
I had infinite circular references

**Comment by CodeShane** [comment]
I might have the same problem; will let you know when I finish counting.
