### ISSUE TITLE
What changed from 2.6.2 to 2.8.2 in fromJson method ?

### ISSUE THREAD

**Issue by raul1991** [google/gson#1661]
input json

{
"constraint":"^\d+$"
}

`Command`

`gson.fromJson(input_json, JsonElement.class)`

**In 2.6.2,**
The fromJson method removes the single '\\'

**In 2.8.2,**

It throws the exception
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 8 column 22 path $[0].constraint
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1014)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:697)
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:893)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)

**Comment by lyubomyr-shaydariv** [comment]
```bash
git log -p gson-parent-2.6.2..gson-parent-2.7 gson/src/main/java/com/google/gson/stream/JsonReader.java
```

There were no many changes but one of them, 3f8726ecafe9c40498255eed1d1893fd665e237b, was the fix you're referring to as your input JSON is invalid since `\d` is not a valid escape sequence:

```diff
diff --git a/gson/src/main/java/com/google/gson/stream/JsonReader.java b/gson/src/main/java/com/google/gson/stream/JsonReader.java
index 7a5e9cbb..20656f6c 100644
--- a/gson/src/main/java/com/google/gson/stream/JsonReader.java
+++ b/gson/src/main/java/com/google/gson/stream/JsonReader.java
@@ -1561,8 +1561,11 @@ public class JsonReader implements Closeable {
     case '\'':
     case '"':
     case '\\':
+    case '/':  
+       return escaped;
     default:
-      return escaped;
+       // throw error when none of the above cases are matched
+       throw syntaxError("Invalid escape sequence");
     }
   }
```

**Comment by raul1991** [comment]
Thanks for clearing it out via code reference.
