### ISSUE TITLE
Unable to deserialize a null property into a JsonObject

### ISSUE THREAD

**Issue by ruke47** [google/gson#1684]
Repro:

```java
import com.google.gson.Gson;
import com.google.gson.JsonObject;

public class GsonDeserialization {

    public static void main(String... args) {
        final Gson gson = new Gson();
        // succeeds
        final MyObject mo1 = gson.fromJson("{ \"name\": null, \"otherProperties\": {} }", MyObject.class);
        // throws
        final MyObject mo2 = gson.fromJson("{ \"name\": \"Alex\", \"otherProperties\": null }", MyObject.class);
    }

    public static class MyObject {
        public String name;
        public JsonObject otherProperties;
    }
}
```
```
Exception in thread "main" com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:896)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at com.andrew.scratch.GsonDeserialization.main(GsonDeserialization.java:13)
```

I would expect the second example to deserialize into an object with a (java) null `otherProperties` member, but instead it throws a JsonSyntaxException.

**Comment by lyubomyr-shaydariv** [comment]
The `JsonElement` hierarchy is a non-null type where null values are represented with `JsonNull.INSTANCE` that is a non-null reference:

- in the read method: https://github.com/google/gson/blob/55acc23d8656a9fe5b19b92029a2dc7277e3765c/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L710
- in the wrapper: https://github.com/google/gson/blob/55acc23d8656a9fe5b19b92029a2dc7277e3765c/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L896

The latter expects `JsonObject`, as you defined it in your mapping, and throws an exception because `JsonNull` is not `JsonObject`. This also can be narrowed down a little:

```java
private static final Gson gson = new GsonBuilder()
		.disableHtmlEscaping()
		.create();

public static void main(final String... args) {
	for ( final String json : new String[]{ "{}", "null" } ) {
		@Nonnull // can never be a null because of how Gson converts null literales to Json* objects
		final JsonElement jsonElement = gson.fromJson(json, JsonElement.class);
		System.out.println(json + ", " + jsonElement.getClass());
	}
}
```

that produces

```
{}, class com.google.gson.JsonObject
null, class com.google.gson.JsonNull
```

Is declaring `otherProperties` as `JsonElement` an option for you?

----

I think that this is an interesting Gson design problem though. The following code throws an exception on read either:

```java
final Object before = null;
final String json = gson.toJson(before, JsonObject.class);
System.out.println(json);
final Object after = gson.fromJson(json, JsonObject.class);
System.out.println(before + " " + after);
```

Even if the code above would return `JsonNull` rather than throwing an exception, it is not symmetric as it I believe supposed to be (the `before` would remain `null` but `after` would be `JsonNull` if read as `JsonElement`). And I think neither `Gson` nor `GsonBuilder` can be patched not breaking the backwards compatibility. If it does not contradict the original author's design, `GsonBuilder` would accept a new flag to convert `null` literals to Java null reference (but not yet clear for which types: `JsonElement` - null or `JsonNull`?; `JsonNull` - null or the `JsonNull.INSTANCE` singleton regardless the configuration?).

**Comment by ruke47** [comment]
> Is declaring otherProperties as `JsonElement` an option for you?

I considered that, but in my use case it was slightly more convenient to declare it a `Map<String, Object>`. (I get a serialization error if a user provides an array or JsonPrimitive, and it's less typing to do a `.has` check.)

I was more concerned about the lack of symmetry, as you pointed out in your second example - I accidentally created a very-simple POJO where Java -> JSON -> Java would throw an unexpected serialization error.

**Comment by Marcono1234** [comment]
I have implemented a possible solution in #1688, though I added a new annotation instead of adding a new option to `GsonBuilder` because an option would affect all classes deserialized with that Gson instance and it could happen that some of them are expecting `null` to be deserialized as `JsonNull`.
What do you think?

**Comment by lyubomyr-shaydariv** [comment]
@Marcono1234 
if I understand it correctly, it wouldn't work for simple `gson.fromJson("null", JsonObject.class)` (+ collections, arrays, maps, etc).

To my understanding, `JsonElement` implies the null object design pattern implementation, where `null` is never permitted in favor of `JsonNull`, and that's probably the idea from the very beginning of Gson. If I'd fix the issue, I'd _probably_ add a new flag to `Gson`/`GsonBuilder`, to preserve backwards compatibility for default `Gson` instances and user code that is not aware of the breaking change. It might change the `JsonElement` type adapter behavior somehow, but I don't see a way of doing it for `TypeAdapters.JSON_ELEMENT` -- it's an anonymous class static intance accepting no constructor arguments, therefore not configurable for different `Gson` instances. Additionally, what if there's user code that refers this instance directly and checks its class for its purposes despite the instance is declared in the `internal` package and not designed for using outside the Gson library explicitly? In short, `TypeAdapters.JSON_ELEMENT` seems to be immutable for anyone now sticking to its behaviro, and using it directly from the user code land makes the bug unfixable. Adding specialized type adapters for each `JsonElement` subtype might resolve the issue, but I guess (have no clear idea on that) there could be two instances per each: one for `null`-friendliness, and one for the default behavior. Next, then: would these type adapters be open as public and how would they affect the performance of reading JSON trees assuming the default `JsonElement` cannot be fixed? Additionally, annotations do not work on all Java elements.

I may be wrong but I find too many concerns and open questions here, and just think that declaring the corresponding fields as `JsonElement` should be fine.

**Comment by Marcono1234** [comment]
I have not made it clear enough, but my pull request was aimed to solve the problem shown in this issue, so it should only apply to fields.
For the simple case `gson.fromJson("null", JsonObject.class)`, the user could simply use `JsonElement` as type instead. Though for generic argument types this would indeed not fix the issue (e.g. `List<JsonObject>`).

- > Additionally, annotations do not work on all Java elements.

    What do you mean by that? Though if Gson was not restricted to Java 6, Java 8's `TYPE_USE` target could be used, so it could possibly (with major rewrites, which are probably not worth it for this feature, though would be a really interesting addition for some point in the future) allow something like
    ```
    private List<@ExplicitlyNullableJsonElement JsonObject> f;
    ```
- > Annotations do not play well for code that cannot be modified.

    In this use-case this might be acceptable because existing code already deals in some way with this problem. However, this problem you mentioned could still arise if you have to use existing types as field types of your class whose source code you cannot edit.

- > For example, it might return JsonNull.INSTANCE like it does now (that conforms the null object pattern), or it might return null that does not conform the null object pattern and may cause NPE.

    I would still go for returning `null` since if a field is not present, its value would be `null` as well. And having to check for both `!= null` and `jsonElement.isJsonNull()` is rather cumbersome.

- > If Gson could have information on field annotations, or type parameter annotations, `@Nullable`/`@Nonnull` would probably be a hint for the "edit 2" above, so Gson could pick the user-declared behavior. But unfortunately, these annotations are not built-ins.

    This is also one reason why I went for **Explicitly**NullableJsonElement. Because currently when you deserialize JSON and a field is simply not present, it will be `null`. Therefore annotations such as `@Nullable` might only imply that the field is optional, but the user might (for whatever reason) not want explicit `null` values.

**Comment by lyubomyr-shaydariv** [comment]
> What do you mean by that?

I was not really clear: I'd rather say that it would be nice to control the nullability contract on the declaration site in call cases, like for fields. For example, Java does not allow processing of `Target.LOCAL_VARIABLE` in runtime. Say, if it would be possible (assuming the mechanics behind that would just work), the following code could work differently for both deseralization calls:

```java
@Nullable
final JsonObject o1 = gson.fromJson("null"); // 1-arg overload, let's assume it can infer the assigned-to variable type with its annotations somehow
...
@Nonnull
final JsonObject o1 = gson.fromJson("null"); // would fail because of JsonNull class cast
```

This is what I meant for annotations.

> In this use-case this might be acceptable because existing code already deals in some way with this problem.

Suppose there is a mapping class that declares a `JsonObject` field by mistake not taking its null object idea into account, and the system claims to guarantee no nulls to occurs. Thus, the issue described in this ticket never happens until someday the null gets there and the old code "proven" to work fails hard. And no original code of the mapping is available to modify: I'd  go with surgering the issue by modifying the type adapter that causes it. Even if I had full control to modify the mapping classes, I'd like to declare the fix once, in `GsonBuilder`.

> I would still go for returning null since if a field is not present, its value would be null as well.

If I'm getting your idea correctly, you mean the undefined/null/value triad here, and yes, no value in the JSON stream would cause `null`, not `JsonNull.INSTANCE`, and the null object pattern seems to be broken the second time. Interesting. So, for data bags, every `JsonElement` field should better be initialized with `JsonNull.INSTANCE` right in the class declaration just to prevent null checks and NPE. Interestingly, the `JSON_ELEMENT` type adapter is implemented in hierarchical manner, but missing fields require post-processing to never be null and conform the null object pattern in full. Bad luck.

> This is also one reason why I went for ExplicitlyNullableJsonElement.

I think this duplicates what JSR-305 annotations do, and your implementation might just probe the JSR-305 annotations in runtime using `Class.forName`. Additionally, I guess, this might also cover non-`JsonElement` issues too, i.e. non-null post-processors etc.

----

The more I think of this issue, the more I like the idea of just putting this pitfall into the documentation only.

**Comment by Marcono1234** [comment]
> The more I think of this issue, the more I like the idea of just putting this pitfall into the documentation only.

Putting it in the documentation is a good idea either way! Do you want to create a pull request?

**Comment by lyubomyr-shaydariv** [comment]
@Marcono1234 
maybe, but I'm not confident that and perhaps there should be a comment from the core team to get their design choice and insight first.
