### ISSUE TITLE
Gson is unable to properly serialize and then deserialize Kotlin HashMap<T1, T2>

### ISSUE THREAD

**Issue by linuxct** [google/gson#1698]
I've written a code in which I am serializing an object to store it and later retrieve it, from within the same application.  

Steps I followed: 
- Setup a data class for the object I'm dealing with

```kotlin
...
import kotlin.collections.HashMap

object AchievementsModel {
    data class UserCalendarModel(var achievementList: HashMap<LocalDateTime, DailyMilestonesAchieved>)
    data class DailyMilestonesAchieved(var achievedA: Boolean, var achievedB: Boolean, var achievedC: Boolean)
}
```

- Set up an initialization and serialization code
```kotlin
val value = AchievementsModel.UserCalendarModel(hashMapOf())
val currentAchievements = value as AchievementsModel.UserCalendarModel
currentAchievements.achievementList[LocalDateTime.now().truncatedTo(ChronoUnit.DAYS)] =
  AchievementsModel.DailyMilestonesAchieved(
    achievedA = false,
    achievedB = false,
    achievedC = false
  )
val gson = Gson()
val serialized = gson.toJson(value)
// Store the value
```

- Check that the serialized contents here are:
```json
{"achievementList":{"2020-05-20T00:00":{"achievedA":false,"achievedB":false,"achievedC":false}}}
```

- Set up a deserialization code
```kotlin
val serialized = //retrieve the value above as String!
val gson = Gson()
gson.fromJson(serialized, AchievementsModel.UserCalendarModel::class.java)
```
Which causes the following exception:
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 22 path $.achievementList.`

I believe because of the way HashMap<T1,T2> is serialized by Gson it expects a different token to begin deserializing it, or I just may be doing something wrong... 

Full Stacktrace: 
```prolog
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 22 path $.achievementList.
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at it.androidclient.Views.ReadActivity$onCreate$$inlined$apply$lambda$1.onClick(ReadActivity.kt:82)
        at android.view.View.performClick(View.java:7259)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27892)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 22 path $.achievementList.
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186) 
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:927) 
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at it.androidclient.Views.ReadActivity$onCreate$$inlined$apply$lambda$1.onClick(ReadActivity.kt:82) 
        at android.view.View.performClick(View.java:7259) 
        at android.view.View.performClickInternal(View.java:7236) 
        at android.view.View.access$3600(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27892) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```  

Edit: I'm currently using com.google.code.gson:gson:2.8.6 on Android Studio 3.6.3, Builtool 29.0.2, Kotlin Runtime version 1.3.71.

**Comment by linuxct** [comment]
The issue is actually the fact Gson is unable to deserialize LocalDateTime properly, not the HashMap, so I was looking at this wrongly all the time. 

The solution went through adding a custom GsonBuilder().registerTypeAdapter specifically for LocalDateTime so it would be able to parse "2020-05-20T00:00" back into a proper date. 

```kotlin
val gson = GsonBuilder().registerTypeAdapter(
  LocalDateTime::class.java,
  JsonDeserializer<Any?> { json, _, _ ->
    LocalDateTime.parse(json.asJsonPrimitive.asString)
  }).create()
gson.fromJson(serialized, AchievementsModel.UserCalendarModel::class.java)
```
