### ISSUE TITLE
java.lang.IllegalStateException: Nesting problem.

### ISSUE THREAD

**Issue by jhwsx** [google/gson#1713]
I want to use custom `TypeAdapter` to serialize a nest class.
But an exception occured:
```text
Exception in thread "main" java.lang.IllegalStateException: Nesting problem.
	at com.google.gson.stream.JsonWriter.beforeValue(JsonWriter.java:655)
	at com.google.gson.stream.JsonWriter.open(JsonWriter.java:326)
	at com.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:309)
	at com.example.gsonlib._01_basic_use.Test$AddressTypeAdapter.write(Test.java:30)
	at com.example.gsonlib._01_basic_use.Test$StudentTypeAdapter.write(Test.java:53)
	at com.example.gsonlib._01_basic_use.Test$StudentTypeAdapter.write(Test.java:41)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at com.example.gsonlib._01_basic_use.Test.main(Test.java:22)
```
My code is the following:
```java
public class Test {
    public static void main(String[] args) {
        Student student = new Student("wzc", 18, new Student.Address("earth"));
        Gson gson2 = new GsonBuilder()
                .serializeNulls()
                .registerTypeAdapter(Student.class, new StudentTypeAdapter(new AddressTypeAdapter()))
                .create();
        String json2 = gson2.toJson(student);
        System.out.println(json2);
    }

    static class AddressTypeAdapter extends TypeAdapter<Student.Address> {

        @Override
        public void write(JsonWriter out, Student.Address value) throws IOException {
            out.beginObject();
            out.name("address").value(value.nation);
            out.endObject();
        }

        @Override
        public Student.Address read(JsonReader in) throws IOException {
            return null;
        }
    }

    static class StudentTypeAdapter extends TypeAdapter<Student> {
        private AddressTypeAdapter mAddressTypeAdapter;

        public StudentTypeAdapter(AddressTypeAdapter addressTypeAdapter) {
            mAddressTypeAdapter = addressTypeAdapter;
        }

        @Override
        public void write(JsonWriter out, Student student) throws IOException {
            out.beginObject()
                    .name("name").value(student.name)
                    .name("age").value(student.age);
            mAddressTypeAdapter.write(out, student.adress);
            out.endObject();
        }

        @Override
        public Student read(JsonReader in) throws IOException {
            return null;
        }
    }
}
```
```java
public class Student {
    public String name;
    public int age;
    public Address adress;

    public Student() {
    }

    public Student(String name, int age, Address adress) {
        this.name = name;
        this.age = age;
        this.adress = adress;
    }

    public static class Address {
        public String nation;

        public Address(String nation) {
            this.nation = nation;
        }
    }
}
```

**Comment by lyubomyr-shaydariv** [comment]
```java
mAddressTypeAdapter.write(out, student.adress);
```

This is a dangling call. Use `out.name("address")` before it.

**Comment by jhwsx** [comment]
@lyubomyr-shaydariv It really works. However, I wonder that what a dangling call means. Moreover, could we have other workaround to solve this problem?

**Comment by lyubomyr-shaydariv** [comment]
@jhwsx 
I meant that Gson prevents your code from creating an illegal JSON document with the "address" property value not bound to the "address" property key, therefore the inner objects would get dangling:

```json
{
  "name": "wzc",
  "age": 18,
  {
    "nation": "Earth"
  }
}
```

Once you fix your code (the error is highlighted red at GitHub), the generated document becomes syntactically correct:

```json
{
  "name": "wzc",
  "age": 18,
  "address": {
    "nation": "Earth"
  }
}
```

**Comment by jhwsx** [comment]
Well, dangling means that I intend to write a value without a corresponding key, which is not allowed by Gson, because of breaking key-value structure. Is my understanding right?

**Comment by lyubomyr-shaydariv** [comment]
@jhwsx 
yes, if you're writing a JSON object (in curly braces `{...}`), you must write key/value pairs. You can't put anonymous values in objects as this is disallowed by the JSON grammar, not Gson (any sane JSON tool would reject such a JSON document).

**Comment by jhwsx** [comment]
Thanks a lot.
