### ISSUE TITLE
Gson taking a lock on SimpleDateFormat

### ISSUE THREAD

**Issue by ferozed** [google/gson#1726]
While debugging a problem in our service, I noticed that `Gson` is using `SimpleDateFormat`. While doing that, it is taking a lock that causes other threads using that same instance of Gson to block...

```
2020-06-22_19:00:26.64218    java.lang.Thread.State: BLOCKED (on object monitor)
2020-06-22_19:00:26.64218       at com.google.gson.DefaultDateTypeAdapter.serialize(DefaultDateTypeAdapter.java:71)
2020-06-22_19:00:26.64218       - waiting to lock <0x00000000d016dc68> (a java.text.SimpleDateFormat)
2020-06-22_19:00:26.64219       at com.google.gson.DefaultDateTypeAdapter.serialize(DefaultDateTypeAdapter.java:37)
2020-06-22_19:00:26.64219       at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
2020-06-22_19:00:26.64220       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
2020-06-22_19:00:26.64220       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
2020-06-22_19:00:26.64220       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
2020-06-22_19:00:26.64221       at com.google.gson.Gson.toJson(Gson.java:669)
2020-06-22_19:00:26.64221       at com.google.gson.Gson.toJson(Gson.java:648)
2020-06-22_19:00:26.64221       at com.google.gson.Gson.toJson(Gson.java:603)
2020-06-22_19:00:26.64221       at com.google.gson.Gson.toJson(Gson.java:583)
```

41 threads waiting on that lock....

```
$ grep -c 'waiting to lock <0x00000000d016dc68>' /opt/app/log/current
41
```
This is with gson-2.8.0

**Comment by lyubomyr-shaydariv** [comment]
* #162
* https://github.com/google/gson/blob/e9ead40302b3466f557a82f924907de59462deb9/gson/src/main/java/com/google/gson/DefaultDateTypeAdapter.java#L71

**Comment by sblommers** [comment]
We are having the same problem, especcially with heavy load. We implemented a custom DateTypeAdapter using FastDateFormat and the troubles went away.

https://github.com/google/gson/issues/162

**Comment by Marcono1234** [comment]
> surely deserves some attention

The underlying issue is that Gson currently uses `java.text.SimpleDateFormat` for the default format, and instances of that class are not thread-safe. Maybe there are ways to improve this though, such as using `ThreadLocal` (might have its drawbacks with [virtual threads](https://openjdk.org/jeps/444)?).

However, in general it would be good if you registered a custom `TypeAdapter` for `java.util.Date` if possible, because the format used by the default adapter is problematic, see #2472. In that custom adapter you can then also use the `java.time.format.DateTimeFormatter` class (converting to `Instant` temporarily) if you want.

**Comment by fireworkit** [comment]
meet this error
