### ISSUE TITLE
A Weird IllegalStateException

### ISSUE THREAD

**Issue by T-zhangshuo** [google/gson#1756]
The Exception information is:
`
java.lang.IllegalStateException	
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:226)	
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(SourceFile:41)	
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(SourceFile:82)	
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(SourceFile:61)	
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(SourceFile:131)	
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:222)	
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(SourceFile:131)	
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:222)	
at com.google.gson.Gson.fromJson(SourceFile:927)	
at com.zdwh.wwdz.net.a.a(SourceFile:45)	
at com.zdwh.wwdz.net.d.a(SourceFile:119)	
at com.zdwh.wwdz.net.d.convertResponse(SourceFile:55)
at com.zdwh.wwdz.net.c.convertResponse(SourceFile:71)	
at com.lzy.okgo.cache.policy.BaseCachePolicy$1.onResponse(SourceFile:163)	
at okhttp3.RealCall$AsyncCall.execute(SourceFile:153)	
at okhttp3.internal.NamedRunnable.run(SourceFile:32)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)	
at java.lang.Thread.run(Thread.java:919)java.lang.IllegalStateException
`

how to fix ?

**Comment by Marcono1234** [comment]
Closing because no further information was provided.
