### ISSUE TITLE
ISO8601UtilsTest failed when System Timezone is between UTC-1 and UTC-12

### ISSUE THREAD

**Issue by ganadist** [google/gson#1780]
In ISO8601UtilsTest.ISO8601UtilsTest, calendar is initiated with Local Timezone.
But ISO8601Utils.format is processing time with UTC, so following error can be raised on UTC-1 and UTC-12

```
$ env TZ=UTC-1 mvn -f gson test

Running com.google.gson.internal.bind.util.ISO8601UtilsTest
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec <<< FAILURE!
testDateFormatString(com.google.gson.internal.bind.util.ISO8601UtilsTest)  Time elapsed: 0.005 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<2018-06-2[5]> but was:<2018-06-2[4]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.google.gson.internal.bind.util.ISO8601UtilsTest.testDateFormatString(ISO8601UtilsTest.java:26)

```

**Comment by eamonnmcmanus** [comment]
Should be fixed by https://github.com/google/gson/pull/1687.
