### ISSUE TITLE
Android desugaring error with 2.8.6 

### ISSUE THREAD

**Issue by ShiremanSun** [google/gson#1827]
when use android.enableD8.desugaring=false

errors Caused by: java.lang.IllegalArgumentException: Type without superclass: module-info

Error while running desugar 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.android.build.gradle.internal.transforms.DesugarWorkerItem$DesugarAction.run(DesugarWorkerItem.java:94)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:50)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:47)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:37)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:37)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.execute(IsolatedClassloaderWorker.java:49)
	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:129)
	at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Type without superclass: module-info
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visit(DefaultMethodClassFixer.java:87)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visit(InterfaceDesugaring.java:106)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:621)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:553)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:431)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:373)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:862)
	... 35 more
Caused by: java.lang.IllegalArgumentException: Type without superclass: module-info

poor english

**Comment by Marcono1234** [comment]
Probably related to #1627

**Comment by Marcono1234** [comment]
Can you please check if this issue still occurs with the latest Gson version? The way the `module-info.class` is included in the Gson JAR was changed and should hopefully now cause fewer issues. Also make sure to use the latest build tools and plugins (e.g. Gradle).

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
