### ISSUE TITLE
withExclusionStrategy native crash

### ISSUE THREAD

**Issue by heweimxcz** [google/gson#1834]
crash heappen in native
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1
    r0  12e17cc8  r1  00000001  r2  00000000  r3  00000001
    r4  702c70f8  r5  702f0ab0  r6  e7c7f070  r7  0004b85f
    r8  00000000  r9  a7351200  r10 702c9950  r11 12e17ca0
    ip  00000338  sp  7e4fac90  lr  7120e4db  pc  7120e500

backtrace:
    #00 pc 0033b500  /system/framework/arm/boot.oat

before native crash,  java stacktrace  is below
java stacktrace:
  at com.google.gson.internal.Excluder.withExclusionStrategy(Excluder.java:101)
  at com.google.gson.GsonBuilder.addSerializationExclusionStrategy(GsonBuilder.java:358)
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
  at com.xxx.httpservice.converter.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:46)
  at com.xxx.httpservice.converter.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:29)
  at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
  at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
  at com.xxx.httpservice.adapter.rxadapter.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:188)
  at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
  at rx.internal.operators.OnSubscribeRedo$2$1.setProducer(OnSubscribeRedo.java:267)
  at com.xxx.httpservice.adapter.rxadapter.OperatorMapResponseToBodyOrError$MapResponseSubscriber.setProducer(OperatorMapResponseToBodyOrError.java:89)
  at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
  at com.xxx.httpservice.adapter.rxadapter.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:165)
  at com.xxx.httpservice.adapter.rxadapter.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:150)
  at rx.Observable.unsafeSubscribe(Observable.java:10346)
  at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
  at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
  at rx.Observable.unsafeSubscribe(Observable.java:10346)
  at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
  at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
  at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
  at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
  at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1.request(OperatorSubscribeOn.java:109)
  at rx.Subscriber.setProducer(Subscriber.java:211)
  at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.setProducer(OperatorSubscribeOn.java:105)
  at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
  at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
  at rx.Observable.unsafeSubscribe(Observable.java:10346)
  at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:919)

i guess this crash happen in,but i am not sure
![image](https://user-images.githubusercontent.com/9306631/101332941-f3c36300-38b0-11eb-9914-e6cef22ae422.png)

**Comment by Marcono1234** [comment]
Are you still experiencing this? Does not occur all the time or did this only occur once?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
