### ISSUE TITLE
  .registerTypeAdapterFactory(GsonJava8TypeAdapterFactory())    when add it crash below 25 api

### ISSUE THREAD

**Issue by heaveninfosoft** [google/gson#1865]
internal val gson = GsonBuilder()
        .registerTypeAdapterFactory(GsonJava8TypeAdapterFactory())
        .registerTypeAdapter(JsonBody::class.java, JsonBodyJsonSerializer())
        .setPrettyPrinting()
        .create()

above line crash

below line not crash

internal val gson = GsonBuilder()
        .registerTypeAdapter(JsonBody::class.java, JsonBodyJsonSerializer())
        .setPrettyPrinting()
        .create()

but that crash on run time 
 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at com.dwolla.util.TokenManagerToken.<init>(TokenManagerToken.kt:11)
        at com.dwolla.util.TokenManager.fetchToken(TokenManager.kt:19)
        at com.dwolla.util.TokenManager.getAccessToken(TokenManager.kt:10)
        at com.dwolla.Dwolla.getAccessToken(Dwolla.kt:34)
        at com.dwolla.DwollaClient.prepareRequest(DwollaClient.kt:285)
        at com.dwolla.DwollaClient.makeRequest(DwollaClient.kt:271)
        at com.dwolla.DwollaClient.get(DwollaClient.kt:74)

**Comment by lyubomyr-shaydariv** [comment]
[java.time | Android Developers](https://developer.android.com/reference/java/time/package-summary) is clear about that:

> Added in API level 26

**Comment by heaveninfosoft** [comment]
So what do if we want to use for all
I mean for all device below and above 26

**Comment by Marcono1234** [comment]
Have a look at https://developer.android.com/studio/write/java8-support#library-desugaring, this will make most `java.time` classes available.

**Comment by Marcono1234** [comment]
Closing because this seems to be unrelated to Gson.
