### ISSUE TITLE
Not able to build it 

### ISSUE THREAD

**Issue by karthik0411** [google/gson#1881]
There are test failures in gson project 
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test

**Comment by Marcono1234** [comment]
Please provide more detail. Though I assume the failing test is `ISO8601UtilsTest`. This has already been reported and there are multiple open pull requests trying to fix it, see for example #1781 and the linked issues and pull requests.

**Comment by karthik0411** [comment]
[INFO] Scanning for projects...

[WARNING]

[WARNING] Some problems were encountered while building the effective model for com.google.code.gson:gson:jar:2.8.6

[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 46, column 15

[WARNING]

[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.

[WARNING]

[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

[WARNING]

[INFO] ------------------------------------------------------------------------

[INFO] Reactor Build Order:

[INFO]

[INFO] Gson Parent                                                        [pom]

[INFO] Gson                                                               [jar]

[INFO]

[INFO] ------------------< com.google.code.gson:gson-parent >------------------

[INFO] Building Gson Parent 2.8.6                                         [1/2]

[INFO] --------------------------------[ pom ]---------------------------------

[INFO]

[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gson-parent ---

[INFO]

[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ gson-parent ---

[INFO]

[INFO] --- maven-install-plugin:2.4:install (default-install) @ gson-parent ---

[INFO] Installing C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\pom.xml to C:\Users\BE20182668\.m2\repository\com\google\code\gson\gson-parent\2.8.6\gson-parent-2.8.6.pom

[INFO]

[INFO] ---------------------< com.google.code.gson:gson >----------------------

[INFO] Building Gson 2.8.6                                                [2/2]

[INFO] --------------------------------[ jar ]---------------------------------

[INFO]

[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gson ---

[INFO] Deleting C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\target

[INFO]

[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ gson ---

[INFO]

[INFO] --- templating-maven-plugin:1.0.0:filter-sources (filtering-java-templates) @ gson ---

[INFO] Coping files with filtering to temporary directory.

[INFO] Using 'UTF-8' encoding to copy filtered resources.

[INFO] Copying 0 resource

[INFO] No files needs to be copied to output directory. Up to date: C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\target\generated-sources\java-templates

[INFO] Source directory: C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\target\generated-sources\java-templates added.

[INFO]

[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gson ---

[INFO] Using 'UTF-8' encoding to copy filtered resources.

[INFO] skip non existing resourceDirectory C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\src\main\resources

[INFO]

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ gson ---

[INFO] Changes detected - recompiling the module!

[INFO] Compiling 74 source files to C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\target\classes

[INFO] /C:/Users/BE20182668/OneDrive - Wipro/Desktop/GradleDemo/gson-gson-parent-2.8.6/gson/src/main/java/com/google/gson/JsonArray.java: Some input files use or override a deprecated API.

[INFO] /C:/Users/BE20182668/OneDrive - Wipro/Desktop/GradleDemo/gson-gson-parent-2.8.6/gson/src/main/java/com/google/gson/JsonArray.java: Recompile with -Xlint:deprecation for details.

[INFO]

[INFO] --- maven-compiler-plugin:3.8.1:compile (base-compile) @ gson ---

[INFO] Changes detected - recompiling the module!

[INFO] Compiling 73 source files to C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\target\classes

[INFO] /C:/Users/BE20182668/OneDrive - Wipro/Desktop/GradleDemo/gson-gson-parent-2.8.6/gson/src/main/java/com/google/gson/JsonArray.java: Some input files use or override a deprecated API.

[INFO] /C:/Users/BE20182668/OneDrive - Wipro/Desktop/GradleDemo/gson-gson-parent-2.8.6/gson/src/main/java/com/google/gson/JsonArray.java: Recompile with -Xlint:deprecation for details.

[INFO]

[INFO] --- bnd-maven-plugin:4.0.0:bnd-process (default) @ gson ---

[WARNING] C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\bnd.bnd [0:0]: Export com.google.gson,  has 1,  private references [com.google.gson.internal],

[INFO]

[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gson ---

[INFO] Using 'UTF-8' encoding to copy filtered resources.

[INFO] skip non existing resourceDirectory C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\src\test\resources

[INFO]

[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ gson ---

[INFO] Changes detected - recompiling the module!

[INFO] Compiling 101 source files to C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\target\test-classes

[INFO] /C:/Users/BE20182668/OneDrive - Wipro/Desktop/GradleDemo/gson-gson-parent-2.8.6/gson/src/test/java/com/google/gson/JsonObjectTest.java: C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\src\test\java\com\google\gson\JsonObjectTest.java uses or overrides a deprecated API.

[INFO] /C:/Users/BE20182668/OneDrive - Wipro/Desktop/GradleDemo/gson-gson-parent-2.8.6/gson/src/test/java/com/google/gson/JsonObjectTest.java: Recompile with -Xlint:deprecation for details.

[INFO]

[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ gson ---

 

-------------------------------------------------------

T E S T S

-------------------------------------------------------

Running com.google.gson.CommentsTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.232 sec - in com.google.gson.CommentsTest

Running com.google.gson.DefaultDateTypeAdapterTest

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.154 sec - in com.google.gson.DefaultDateTypeAdapterTest

Running com.google.gson.DefaultInetAddressTypeAdapterTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in com.google.gson.DefaultInetAddressTypeAdapterTest

Running com.google.gson.DefaultMapJsonSerializerTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec - in com.google.gson.DefaultMapJsonSerializerTest

Running com.google.gson.ExposeAnnotationExclusionStrategyTest

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in com.google.gson.ExposeAnnotationExclusionStrategyTest

Running com.google.gson.FieldAttributesTest

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.google.gson.FieldAttributesTest

Running com.google.gson.functional.ArrayTest

Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.067 sec - in com.google.gson.functional.ArrayTest

Running com.google.gson.functional.CircularReferenceTest

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 sec - in com.google.gson.functional.CircularReferenceTest

Running com.google.gson.functional.CollectionTest

Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.138 sec - in com.google.gson.functional.CollectionTest

Running com.google.gson.functional.ConcurrencyTest

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.14 sec - in com.google.gson.functional.ConcurrencyTest

Running com.google.gson.functional.CustomDeserializerTest

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec - in com.google.gson.functional.CustomDeserializerTest

Running com.google.gson.functional.CustomSerializerTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec - in com.google.gson.functional.CustomSerializerTest

Running com.google.gson.functional.CustomTypeAdaptersTest

Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.062 sec - in com.google.gson.functional.CustomTypeAdaptersTest

Running com.google.gson.functional.DefaultTypeAdaptersTest

Tests run: 65, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.088 sec - in com.google.gson.functional.DefaultTypeAdaptersTest

Running com.google.gson.functional.DelegateTypeAdapterTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.google.gson.functional.DelegateTypeAdapterTest

Running com.google.gson.functional.EnumTest

Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.google.gson.functional.EnumTest

Running com.google.gson.functional.EscapingTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.functional.EscapingTest

Running com.google.gson.functional.ExclusionStrategyFunctionalTest

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec - in com.google.gson.functional.ExclusionStrategyFunctionalTest

Running com.google.gson.functional.ExposeFieldsTest

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.035 sec - in com.google.gson.functional.ExposeFieldsTest

Running com.google.gson.functional.FieldExclusionTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in com.google.gson.functional.FieldExclusionTest

Running com.google.gson.functional.FieldNamingTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in com.google.gson.functional.FieldNamingTest

Running com.google.gson.functional.GsonVersionDiagnosticsTest

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec <<< FAILURE! - in com.google.gson.functional.GsonVersionDiagnosticsTest

testAssertionErrorInDeserializationPrintsVersion(com.google.gson.functional.GsonVersionDiagnosticsTest)  Time elapsed: 0.009 sec  <<< FAILURE!

junit.framework.AssertionFailedError

        at com.google.gson.functional.GsonVersionDiagnosticsTest.ensureAssertionErrorPrintsGsonVersion(GsonVersionDiagnosticsTest.java:89)

        at com.google.gson.functional.GsonVersionDiagnosticsTest.testAssertionErrorInDeserializationPrintsVersion(GsonVersionDiagnosticsTest.java:76)

 

testAssertionErrorInSerializationPrintsVersion(com.google.gson.functional.GsonVersionDiagnosticsTest)  Time elapsed: 0.001 sec  <<< FAILURE!

junit.framework.AssertionFailedError

        at com.google.gson.functional.GsonVersionDiagnosticsTest.ensureAssertionErrorPrintsGsonVersion(GsonVersionDiagnosticsTest.java:89)

        at com.google.gson.functional.GsonVersionDiagnosticsTest.testAssertionErrorInSerializationPrintsVersion(GsonVersionDiagnosticsTest.java:66)

 

Running com.google.gson.functional.InheritanceTest

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.google.gson.functional.InheritanceTest

Running com.google.gson.functional.InstanceCreatorTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in com.google.gson.functional.InstanceCreatorTest

Running com.google.gson.functional.InterfaceTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.google.gson.functional.InterfaceTest

Running com.google.gson.functional.InternationalizationTest

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.google.gson.functional.InternationalizationTest

Running com.google.gson.functional.JavaUtilConcurrentAtomicTest

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.google.gson.functional.JavaUtilConcurrentAtomicTest

Running com.google.gson.functional.JavaUtilTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.04 sec - in com.google.gson.functional.JavaUtilTest

Running com.google.gson.functional.JsonAdapterAnnotationOnClassesTest

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in com.google.gson.functional.JsonAdapterAnnotationOnClassesTest

Running com.google.gson.functional.JsonAdapterAnnotationOnFieldsTest

Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in com.google.gson.functional.JsonAdapterAnnotationOnFieldsTest

Running com.google.gson.functional.JsonAdapterSerializerDeserializerTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec - in com.google.gson.functional.JsonAdapterSerializerDeserializerTest

Running com.google.gson.functional.JsonArrayTest

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.google.gson.functional.JsonArrayTest

Running com.google.gson.functional.JsonParserTest

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in com.google.gson.functional.JsonParserTest

Running com.google.gson.functional.JsonTreeTest

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.google.gson.functional.JsonTreeTest

Running com.google.gson.functional.LeniencyTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.functional.LeniencyTest

Running com.google.gson.functional.MapAsArrayTypeAdapterTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in com.google.gson.functional.MapAsArrayTypeAdapterTest

Running com.google.gson.functional.MapTest

Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.182 sec - in com.google.gson.functional.MapTest

Running com.google.gson.functional.MoreSpecificTypeSerializationTest

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec - in com.google.gson.functional.MoreSpecificTypeSerializationTest

Running com.google.gson.functional.NamingPolicyTest

Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.029 sec - in com.google.gson.functional.NamingPolicyTest

Running com.google.gson.functional.NullObjectAndFieldTest

Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec - in com.google.gson.functional.NullObjectAndFieldTest

Running com.google.gson.functional.ObjectTest

Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 sec - in com.google.gson.functional.ObjectTest

Running com.google.gson.functional.ParameterizedTypesTest

Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec - in com.google.gson.functional.ParameterizedTypesTest

Running com.google.gson.functional.PrettyPrintingTest

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.google.gson.functional.PrettyPrintingTest

Running com.google.gson.functional.PrimitiveCharacterTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.functional.PrimitiveCharacterTest

Running com.google.gson.functional.PrimitiveTest

Tests run: 99, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec - in com.google.gson.functional.PrimitiveTest

Running com.google.gson.functional.PrintFormattingTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.google.gson.functional.PrintFormattingTest

Running com.google.gson.functional.RawSerializationTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.google.gson.functional.RawSerializationTest

Running com.google.gson.functional.ReadersWritersTest

Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.google.gson.functional.ReadersWritersTest

Running com.google.gson.functional.RuntimeTypeAdapterFactoryFunctionalTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.google.gson.functional.RuntimeTypeAdapterFactoryFunctionalTest

Running com.google.gson.functional.SecurityTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.functional.SecurityTest

Running com.google.gson.functional.SerializedNameTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.functional.SerializedNameTest

Running com.google.gson.functional.StreamingTypeAdaptersTest

Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.043 sec - in com.google.gson.functional.StreamingTypeAdaptersTest

Running com.google.gson.functional.StringTest

Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in com.google.gson.functional.StringTest

Running com.google.gson.functional.ThrowableFunctionalTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.google.gson.functional.ThrowableFunctionalTest

Running com.google.gson.functional.TreeTypeAdaptersTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.google.gson.functional.TreeTypeAdaptersTest

Running com.google.gson.functional.TypeAdapterPrecedenceTest

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in com.google.gson.functional.TypeAdapterPrecedenceTest

Running com.google.gson.functional.TypeHierarchyAdapterTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in com.google.gson.functional.TypeHierarchyAdapterTest

Running com.google.gson.functional.TypeVariableTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.google.gson.functional.TypeVariableTest

Running com.google.gson.functional.UncategorizedTest

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.google.gson.functional.UncategorizedTest

Running com.google.gson.functional.VersioningTest

Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec - in com.google.gson.functional.VersioningTest

Running com.google.gson.GenericArrayTypeTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.google.gson.GenericArrayTypeTest

Running com.google.gson.GsonBuilderTest

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.GsonBuilderTest

Running com.google.gson.GsonTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.google.gson.GsonTest

Running com.google.gson.GsonTypeAdapterTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.google.gson.GsonTypeAdapterTest

Running com.google.gson.InnerClassExclusionStrategyTest

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.InnerClassExclusionStrategyTest

Running com.google.gson.internal.bind.JsonElementReaderTest

Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.google.gson.internal.bind.JsonElementReaderTest

Running com.google.gson.internal.bind.JsonTreeReaderTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in com.google.gson.internal.bind.JsonTreeReaderTest

Running com.google.gson.internal.bind.JsonTreeWriterTest

Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec - in com.google.gson.internal.bind.JsonTreeWriterTest

Running com.google.gson.internal.bind.RecursiveTypesResolveTest

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in com.google.gson.internal.bind.RecursiveTypesResolveTest

Running com.google.gson.internal.GsonBuildConfigTest

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE! - in com.google.gson.internal.GsonBuildConfigTest

testEnsureGsonBuildConfigGetsUpdatedToMavenVersion(com.google.gson.internal.GsonBuildConfigTest)  Time elapsed: 0.001 sec  <<< FAILURE!

java.lang.AssertionError

        at com.google.gson.internal.GsonBuildConfigTest.testEnsureGsonBuildConfigGetsUpdatedToMavenVersion(GsonBuildConfigTest.java:31)

 

Running com.google.gson.internal.GsonTypesTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.internal.GsonTypesTest

Running com.google.gson.internal.JavaVersionTest

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.internal.JavaVersionTest

Running com.google.gson.internal.LazilyParsedNumberTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.google.gson.internal.LazilyParsedNumberTest

Running com.google.gson.internal.LinkedHashTreeMapTest

Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.internal.LinkedHashTreeMapTest

Running com.google.gson.internal.LinkedTreeMapTest

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.google.gson.internal.LinkedTreeMapTest

Running com.google.gson.internal.reflect.UnsafeReflectionAccessorTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.google.gson.internal.reflect.UnsafeReflectionAccessorTest

Running com.google.gson.internal.UnsafeAllocatorInstantiationTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in com.google.gson.internal.UnsafeAllocatorInstantiationTest

Running com.google.gson.JavaSerializationTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec - in com.google.gson.JavaSerializationTest

Running com.google.gson.JsonArrayTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.google.gson.JsonArrayTest

Running com.google.gson.JsonNullTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec - in com.google.gson.JsonNullTest

Running com.google.gson.JsonObjectTest

Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.google.gson.JsonObjectTest

Running com.google.gson.JsonParserTest

Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.061 sec - in com.google.gson.JsonParserTest

Running com.google.gson.JsonPrimitiveTest

Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 sec - in com.google.gson.JsonPrimitiveTest

Running com.google.gson.JsonStreamParserTest

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.google.gson.JsonStreamParserTest

Running com.google.gson.LongSerializationPolicyTest

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.google.gson.LongSerializationPolicyTest

Running com.google.gson.metrics.PerformanceTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.metrics.PerformanceTest

Running com.google.gson.MixedStreamTest

Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.MixedStreamTest

Running com.google.gson.ObjectTypeAdapterTest

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.google.gson.ObjectTypeAdapterTest

Running com.google.gson.OverrideCoreTypeAdaptersTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.google.gson.OverrideCoreTypeAdaptersTest

Running com.google.gson.ParameterizedTypeTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.google.gson.ParameterizedTypeTest

Running com.google.gson.reflect.TypeTokenTest

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in com.google.gson.reflect.TypeTokenTest

Running com.google.gson.regression.JsonAdapterNullSafeTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.google.gson.regression.JsonAdapterNullSafeTest

Running com.google.gson.stream.JsonReaderPathTest

Tests run: 20, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in com.google.gson.stream.JsonReaderPathTest

Running com.google.gson.stream.JsonReaderTest

Tests run: 120, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.google.gson.stream.JsonReaderTest

Running com.google.gson.stream.JsonWriterTest

Tests run: 39, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in com.google.gson.stream.JsonWriterTest

Running com.google.gson.VersionExclusionStrategyTest

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in com.google.gson.VersionExclusionStrategyTest

 

Results :

 

Failed tests:

  GsonVersionDiagnosticsTest.testAssertionErrorInDeserializationPrintsVersion:76->ensureAssertionErrorPrintsGsonVersion:89

  GsonVersionDiagnosticsTest.testAssertionErrorInSerializationPrintsVersion:66->ensureAssertionErrorPrintsGsonVersion:89

  GsonBuildConfigTest.testEnsureGsonBuildConfigGetsUpdatedToMavenVersion:31

 

Tests run: 1051, Failures: 3, Errors: 0, Skipped: 1

 

[INFO] ------------------------------------------------------------------------

[INFO] Reactor Summary for Gson Parent 2.8.6:

[INFO]

[INFO] Gson Parent ........................................ SUCCESS [  1.754 s]

[INFO] Gson ............................................... FAILURE [ 42.441 s]

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  44.676 s

[INFO] Finished at: 2021-04-08T12:47:39+05:30

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project gson: There are test failures.

[ERROR]

[ERROR] Please refer to C:\Users\BE20182668\OneDrive - Wipro\Desktop\GradleDemo\gson-gson-parent-2.8.6\gson\target\surefire-reports for the individual test results.

[ERROR] -> [Help 1]

[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

[ERROR]

[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <args> -rf :gson

**Comment by Marcono1234** [comment]
Could you please edit your comment and only include the relevant test failure snippets?
Additionally all the failures seem to be related to verifying the version information `GsonBuildConfig.VERSION`, have you modified the code in some way by any chance?
If not, could you please run the tests in debug mode in your IDE and find out which value `GsonBuildConfig.VERSION` has, and why it does not match?

**Comment by inder123** [comment]
Thanks @Marcono1234 for helping out with comments on various issues and PRs. You are an invaluable supporter of this project.

**Comment by Marcono1234** [comment]
Thanks @inder123 for these kind words!
Though what are the plans with Gson (see #1821)? Users are starting to switch to other libraries. And contributors might become discouraged because their contribution is never included.

**Comment by eamonnmcmanus** [comment]
Closing due to inactivity. [These questions](https://github.com/google/gson/issues/1881#issuecomment-816144843) were never answered.
