### ISSUE TITLE
Integer overflow when calling `fromJson()` on `JsonObject`

### ISSUE THREAD

**Issue by mroloux** [google/gson#1994]
# Gson version
2.8.8

# Java / Android version
11

# Description
I'm using `fromJson()` to convert between a `JsonObject` and a POJO. When the `JsonObject` has a `long` primitive property, and I convert to an `int` on the POJO, an overflow occurs.

On the other hand, when I convert from string to the POJO, an exception gets thrown (as expected).

## Expected behavior
Exception when putting a `long` primitive value in an `int` property in `fromJson()`.

## Actual behavior
No exception, but incorrectly set `int` property.

# Reproduction steps

```
package domain.drawing;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

public class MyClass {

    public int foo;

    public static void main(String[] args) {
        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("foo", 10000000000L);
        System.out.println("-- fromJson on JsonObject: ");
        System.out.println(new Gson().fromJson(jsonObject, MyClass.class));

        System.out.println("");
        System.out.println("-- fromJson on string: ");
        System.out.println(new Gson().fromJson("{foo: 10000000000}", MyClass.class));
    }

    @Override
    public String toString() {
        return Integer.toString(foo);
    }
}
```

Running this main method outputs:

```
-- fromJson on JsonObject: 
1410065408

-- fromJson on string: 
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 10000000000 at line 1 column 18 path $.foo
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:231)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:221)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at domain.drawing.MyClass.main(MyClass.java:18)
Caused by: java.lang.NumberFormatException: Expected an int but was 10000000000 at line 1 column 18 path $.foo
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1171)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:229)
	... 8 more

Process finished with exit code 1
```

**Comment by komminen** [comment]
Hi, we will volunteer to work on this issue in October/November. For the project maintainer, please let us know if this is okay and if you want it fixed.

**Comment by NatalieSty** [comment]
@mroloux Hi there,

I tried to reproduce this bug, but it seems like it is already throwing an exception:

`  public void testIntOverflow() {
    class MyClassTest{
      public int foo;
    }
    JsonObject jsonObject = new JsonObject();
    jsonObject.addProperty("foo", 10000000000L);
    System.out.println("-- fromJson on JsonObject: ");
    MyClassTest test = new Gson().fromJson(jsonObject, MyClassTest.class);
    System.out.println(test.foo);
  }`

Output:
`-- fromJson on JsonObject: 

java.lang.NullPointerException
	at com.google.gson/com.google.gson.JsonObjectTest.testIntOverflow(JsonObjectTest.java:210)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

`

**Comment by Marcono1234** [comment]
There seem to be backward compatibility concerns, see https://github.com/google/gson/pull/2031#issuecomment-987030702:
> Although we could imagine tweaks to allow these cases to continue to work, or perhaps to update the tests so they don't trigger the problems, my feeling is that it is probably best to leave well enough alone. So I am probably going to close this PR and the associated issue.
