### ISSUE TITLE
module java.base does not "opens java.io" to unnamed

### ISSUE THREAD

**Issue by sbasurto** [google/gson#2140]
# Gson version 2.9.1

# Java version openjdk version "17.0.3" 2022-04-19

# Used tools

Maven home: /usr/share/maven-bin-3.8
Java version: 17.0.3, vendor: Gentoo, runtime: /usr/lib64/openjdk-17
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.41-gentoo", arch: "amd64", family: "unix"
Tomcat version:  10.0.21-gentoo

# Description

I use Gson in a jsp tag as follows:

```
MyVerySimpleClass myClass = gson.fromJson(jsonString, MyVerySimpleClass.class);
```
And receive the following exception:

```
threw exception [jakarta.servlet.ServletException: jakarta.servlet.jsp.JspException: com.google.gson.JsonIOException: Failed making field 'java.io.OutputStreamWriter#se' accessible; either change its visibility or write a custom TypeAdapter for its declaring type] with root cause
        java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.nio.cs.StreamEncoder java.io.OutputStreamWriter.se accessible: module java.base does not "opens java.io" to unnamed module @381ee76
```
## Expected behavior

That the JSON string be converted to the class specified.

## Actual behavior

The exception break my code.

# Reproduction steps
1. Use method fromJson within a jsp tag file.

## My work around
I inspect Gson code and found where the problem were so I modify: 

```
diff --git a/gson/src/main/java/com/google/gson/internal/reflect/ReflectionHelper.java b/gson/src/main/java/com/google/gson/internal/reflect/ReflectionHelper.java
index 97230ff6..33fefd0a 100644
--- a/gson/src/main/java/com/google/gson/internal/reflect/ReflectionHelper.java
+++ b/gson/src/main/java/com/google/gson/internal/reflect/ReflectionHelper.java
@@ -16,15 +16,26 @@ public class ReflectionHelper {
    * @throws JsonIOException if making the field accessible fails
    */
   public static void makeAccessible(Field field) throws JsonIOException {
-    try {
-      field.setAccessible(true);
+    try {        
+        if(!isJavaBase(field.getDeclaringClass().getName())) {
+            field.setAccessible(true);
+        }
     } catch (Exception exception) {
-      throw new JsonIOException("Failed making field '" + field.getDeclaringClass().getName() + "#"
+      throw new JsonIOException("Orale mano, Failed making field '" + field.getDeclaringClass().getName() + "#"
           + field.getName() + "' accessible; either change its visibility or write a custom "
           + "TypeAdapter for its declaring type", exception);
     }
   }
 
+  public static boolean isJavaBase(String className) {
+       return  className.contains("java.io") || 
+                className.contains("sun.nio") ||
+                className.contains("java.nio")||
+                className.contains("java.lang")||
+                className.contains("java.util")||
+                className.contains("jdk.internal");
+  }
+
``` 
After doing this modification I received another Exception: 

```
threw exception [jakarta.servlet.ServletException: jakarta.servlet.jsp.JspException: java.lang.IllegalArgumentException: jdk.internal.ref.PhantomCleanable<?> declares multiple JSON fields named next] with root cause
        java.lang.IllegalArgumentException: jdk.internal.ref.PhantomCleanable<?> declares multiple JSON fields named next
```

So I changed this other file:

```
diff --git a/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java b/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java
index 1687889b..761f3d5a 100644
--- a/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java
+++ b/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java
@@ -172,10 +172,17 @@ public final class ReflectiveTypeAdapterFactory implements TypeAdapterFactory {
       }
     };
   }
-
+       public static boolean isJavaBase(String className) {
+               return  className.contains("java.io") ||
+                       className.contains("sun.nio") ||
+                       className.contains("java.nio")||
+                       className.contains("java.lang")||
+                        className.contains("java.util")||
+                       className.contains("jdk.internal");
+       }
        private Map<String, BoundField> getBoundFields(Gson context, TypeToken<?> type, Class<?> raw, boolean blockInaccessible) {
                Map<String, BoundField> result = new LinkedHashMap<>();
-    if (raw.isInterface()) {
+               if (raw.isInterface() || isJavaBase(raw.getName())) {
                        return result;
                }
```
After those changes everything is working, this works for me because **I do not use Gson to get java base classes from a JSON string**.

# Exception stack trace

```
01-Jul-2022 09:17:20.538 SEVERE [http-nio-8080-exec-21] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/g-wms2] threw exception [jakarta.servlet.ServletException: jakarta.servlet.jsp.JspException: com.google.gson.JsonIOException: Orales mano, esto está mas ca, de lo que pensé, Failed making field 'java.io.OutputStreamWriter#se' accessible; either change its visibility or write a custom TypeAdapter for its declaring type] with root cause
        java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.nio.cs.StreamEncoder java.io.OutputStreamWriter.se accessible: module java.base does not "opens java.io" to unnamed module @381ee76
                at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
                at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
                at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
                at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
                at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:20)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:207)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:141)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:215)
                at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:116)
                at com.google.gson.Gson.getAdapter(Gson.java:531)
                at com.google.gson.Gson.fromJson(Gson.java:1057)
                at com.google.gson.Gson.fromJson(Gson.java:1016)
                at com.google.gson.Gson.fromJson(Gson.java:959)
                at com.google.gson.Gson.fromJson(Gson.java:927)
                at org.apache.jsp.tag.meta.META_002dINF.gatorApps_tld.kpis.gator_005fapp_005fkpi_005fboard_tag.doTag(gator_005fapp_005fkpi_005fboard_tag.java:149)
                at org.apache.jsp.forms.kpis_005fboard_jsp._jspService(kpis_005fboard_jsp.java:359)
                at org.apache.jasper.runtime.HttpJspBase.service(Unknown Source)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:777)
                at org.apache.jasper.servlet.JspServletWrapper.service(Unknown Source)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(Unknown Source)
                at org.apache.jasper.servlet.JspServlet.service(Unknown Source)
                at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:777)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(Unknown Source)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
                at org.apache.catalina.core.StandardWrapperValve.invoke(Unknown Source)
                at org.apache.catalina.core.StandardContextValve.invoke(Unknown Source)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Unknown Source)
                at org.apache.catalina.core.StandardHostValve.invoke(Unknown Source)
                at org.apache.catalina.valves.ErrorReportValve.invoke(Unknown Source)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(Unknown Source)
                at org.apache.catalina.core.StandardEngineValve.invoke(Unknown Source)
                at org.apache.catalina.connector.CoyoteAdapter.service(Unknown Source)
                at org.apache.coyote.http11.Http11Processor.service(Unknown Source)
                at org.apache.coyote.AbstractProcessorLight.process(Unknown Source)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Unknown Source)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(Unknown Source)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(Unknown Source)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(Unknown Source)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(Unknown Source)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(Unknown Source)
```

**Comment by Marcono1234** [comment]
Could you please create a small example project which showcases this issue and provide instructions for running that project?
I am not familiar with JSP Tag, but I am not a member of this project. So maybe the members are more familiar with JSP.

**Comment by sbasurto** [comment]
Sure I will do that and let you know. I try to have it on Tuesday 05 of July.
