### ISSUE TITLE
why cant  CloseableHttpResponse be serialized

### ISSUE THREAD

**Issue by hexuxu110** [google/gson#2141]
why?

java.lang.StackOverflowError: null
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401)
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:479)
	at com.google.gson.internal.bind.TypeAdapters$3.write(TypeAdapters.java:148)
	at com.google.gson.internal.bind.TypeAdapters$3.write(TypeAdapters.java:133)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)

**Comment by Marcono1234** [comment]
Possibly because internally it has a cyclic reference to itself. However, the bigger problem here is that you are using Gson's reflection-based serialization on third-party classes. You should avoid this because you are accessing the implementation details of these classes this way, which may change at any point. Instead, serialize only the relevant data, for example the response body as String, or create a custom model class which contains all the relevant data from the response.

**Comment by eamonnmcmanus** [comment]
Thanks @Marcono1234 for the analysis. Indeed, I don't think it is wise to use reflection-based serialization here.
