### ISSUE TITLE
Module-info.class throwing java.lang.ArrayIndexOutOfBoundsException: 19

### ISSUE THREAD

**Issue by saurabhgupta1233** [google/gson#2165]
# Gson version

Failing on 2.8.9, 2.9.0, 2.9.1 
Working fine on 2.8.1

# Java / Android version

Java 8 (Open JDK)

# Used tools

- [x] Maven; version: Apache Maven 3.5.4

# Description

While trying to package the maven

## Expected behavior

It should provide build success

## Actual behavior

It fails and throws below stacktrace

# Reproduction steps

1. I am using atlas sdk for building this. I can give you steps on how to set it up, if you are interested.
2. ...

# Exception stack trace

```
[INFO] --- maven-confluence-plugin:6.3.15:generate-manifest (default-generate-manifest) @ project ---
[INFO] Generating a manifest for this plugin
[INFO] using maven-bundle-plugin v2.5.3
java.lang.ArrayIndexOutOfBoundsException: 19
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:579)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:497)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:486)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:476)
	at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2195)
	at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2132)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:139)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:352)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:618)
	at org.apache.felix.bundleplugin.ManifestPlugin.getAnalyzer(ManifestPlugin.java:213)
	at org.apache.felix.bundleplugin.ManifestPlugin.getManifest(ManifestPlugin.java:114)
	at org.apache.felix.bundleplugin.ManifestPlugin.execute(ManifestPlugin.java:69)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:294)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:285)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojoImpl(MojoExecutor.java:172)
	at org.twdata.maven.mojoexecutor.MojoExecutor$ExecutionEnvironmentM3.executeMojo(MojoExecutor.java:476)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:75)
	at com.atlassian.maven.plugins.amps.MavenGoals.generateBundleManifest(MavenGoals.java:1593)
	at com.atlassian.maven.plugins.amps.osgi.GenerateManifestMojo.execute(GenerateManifestMojo.java:65)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
java.lang.ArrayIndexOutOfBoundsException: 19
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:579)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:497)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:486)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:476)
	at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2195)
	at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2132)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:139)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:352)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:618)
	at org.apache.felix.bundleplugin.ManifestPlugin.getAnalyzer(ManifestPlugin.java:213)
	at org.apache.felix.bundleplugin.ManifestPlugin.getManifest(ManifestPlugin.java:114)
	at org.apache.felix.bundleplugin.ManifestPlugin.execute(ManifestPlugin.java:69)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:294)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:285)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojoImpl(MojoExecutor.java:172)
	at org.twdata.maven.mojoexecutor.MojoExecutor$ExecutionEnvironmentM3.executeMojo(MojoExecutor.java:476)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:75)
	at com.atlassian.maven.plugins.amps.MavenGoals.generateBundleManifest(MavenGoals.java:1593)
	at com.atlassian.maven.plugins.amps.osgi.GenerateManifestMojo.execute(GenerateManifestMojo.java:65)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Manifest company:name:version : Unused Import-Package instructions: [org.springframework.osgi.*, org.eclipse.gemini.blueprint.*]
[ERROR] Manifest company:name:version : Exception: 19
[ERROR] Manifest company:name:version : Invalid class file META-INF/versions/9/module-info.class (java.lang.ArrayIndexOutOfBoundsException: 19)
[ERROR] Manifest company:name:version : Exception: 19
[ERROR] Manifest company:name:version : Invalid class file module-info.class (java.lang.ArrayIndexOutOfBoundsException: 19)
[ERROR] Error(s) found in manifest configuration
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.374 s
[INFO] Finished at: 2022-08-03T16:59:14-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.atlassian.maven.plugins:maven-confluence-plugin:6.3.15:generate-manifest (default-generate-manifest) on project project : Unable to execute mojo: Error(s) found in manifest configuration -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by Marcono1234** [comment]
Can you please try updating the Maven Bundle Plugin and let us know if that helped? It looks like this specific issue was [fixed in version 3.5.0](https://issues.apache.org/jira/browse/FELIX-5698).

In case that is used internally by maven-confluence-plugin, maybe try to update that plugin or try updating the Maven Bundle Plugin by [configuring the plugin depenencies](https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_dependencies_Tag) of maven-confluence-plugin.

**Comment by saurabhgupta1233** [comment]
Hi,
I tried 3.5.4 & 3.8.6. None of them fixed the issue.

**Comment by Marcono1234** [comment]
> I tried 3.5.4 & 3.8.6. None of them fixed the issue.

Which plugin are you talking about? It looks like `org.apache.felix:maven-bundle-plugin` does not have these versions. Could you please create a small self-contained example project (`pom.xml` might already suffice) which allows reproducing this?

**Comment by saurabhgupta1233** [comment]
Hi again, 
While trying to create a sample program for you to debug. I was able to resolve the issue. For anyone else reading this, here's what I did as suggested by @Marcono1234 

`<groupId>com.atlassian.maven.plugins</groupId>`
`<artifactId>confluence-maven-plugin</artifactId>`
`<version>${amps.version}</version>`

Increased the amps.version from **6.3.15** to **8.2.3**. 
(After bumping up the version. It did require some refactoring to get the whole thing to work, but the error messages were clear enough in my case)
Thanks Marcono.
