### ISSUE TITLE
Strings with characters " and \ causing issues when parsing to class using fromJSON

### ISSUE THREAD

**Issue by pjoe** [google/gson#2244]
# Gson version
2.10

# Java / Android version
openjdk version "17.0.3"

# Used tools
- [x] Maven; version: Apache Maven 3.8.5

# Description
When using `fromJSON` to parse JSON into a class with a String member and the source JSON string contains `"` or `\`, then GSON will either produce wrong string or throw an exception. This particularly comes into play when the payload is random generated password.

## Expected behavior
JSON string to be parsed correctly.

## Actual behavior
Resulting string doesn't match the input or GSON throws an exception.

# Reproduction steps
Repl reproducing this, including fuzzer: https://replit.com/@pjoePanda/GSON-fuzzy-test#Main.java

Pasting code here also:
```java
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.util.Random;

public class Main {
  static class Result {
    boolean success;
    String message;

    Result(boolean success, String message) {
      this.success = success;
      this.message = message;
    }
  }

  public static void main(String[] args) {
    String[] passwords = {
        "p01-foo",
        "p02-foo\"bar",
        "p03-foo/bar",
        "p04-foo\\bar",
        "p05-foo$bar",
        "p06-foo'bar",
        "p07-foobar/",
        "p08-foobar/\\",
    };

    for (String password : passwords) {
      var result = testPassword(password);
      if (!result.success) {
        System.out.println("❌ %s: %s".formatted(password, result.message));
      }
    }
    System.out.println();

    // loop until 20 fails or 10000 iterations
    int fails = 0;
    for (int i = 0; i < 10000 && fails < 40; ++i) {
      var password = generateRandomString(8);      
      var result = testPassword(password);
      if (!result.success) {
        ++fails;
        System.out.println("❌ %s: %s".formatted(password, result.message));
      }
    }
  }

  static Random random = new Random(768345);

  static String generateRandomString(int length) {
    var chars = "\"\\!#$%&/()[]{}=-+'^,.;:_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    var randomString = "";
    for (int i = 0; i < length; i++) {
      randomString += chars.charAt(Math.abs(random.nextInt( chars.length())));
    }
    return randomString;
  }

  static class Creds {
    String password;
  }

  public static Result testPassword(String password) {
    String jsonString = "{ \"password\": \"%s\" }".formatted(password);
    Gson GSON = new GsonBuilder().create();
    try {
      Creds creds = GSON.fromJson(jsonString, Creds.class);
      if (creds.password.equals(password)) {
        return new Result(true, creds.password);
      } else {
        return new Result(false, creds.password);
      }
    } catch (Exception e) {
      return new Result(false, "Error");
    }
  }
}
```

Which gives following output:
```
❌ p02-foo"bar: Error
❌ p04-foo\bar: p04-foar
❌ p08-foobar/\: Error

❌ "N,+r.g-: Error
❌ W\:7bQe[: Error
❌ l"Fnqaee: Error
❌ ZDJ=I&u": Error
❌ )"/V]B6": Error
❌ o"oQ7vd]: Error
❌ s6SwH8p\: Error
❌ L]rEu".L: Error
❌ ,&2C_R\E: Error
❌ r'!Ou\I_: Error
❌ 1n6F%K=\: Error
❌ 9)\BQiP3: Error
❌ XNeB\Ix+: Error
❌ WTca"Z#}: Error
❌ kwfYp"Tk: Error
❌ ("ZNt1)%: Error
❌ )\k^w=Dg: Error
❌ .:\z]F}0: Error
❌ "F;'rFDi: Error
❌ qmV3\wQV: Error
❌ B.k%^W\z: Error
❌ %]hF^3"s: Error
❌ jJ{KeB!\: Error
❌ H\v)xy=#: Error
❌ Xgq7%\{J: Error
❌ qeRg9("^: Error
❌ rl\S#VM): Error
❌ vE\z5KJB: Error
❌ maS(\v7}: Error
❌ :P/QL"o6: Error
❌ =f5w"}!g: Error
❌ S8A"VK!Y: Error
❌ ,!"D8)Ts: Error
❌ \D%8KjdF: Error
❌ -Kg%"{wW: Error
❌ "JiCTR]C: Error
❌ V/l$\w+D: Error
❌ [sar\FN;: Error
❌ Z!}Wv\{o: Error
❌ WKNp"Nho: Error
```

# Exception stack trace

```
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 21 path $.password
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at HelloWorld.main(HelloWorld.java:18)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 21 path $.password
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:492)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:894)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 4 more

```

**Comment by eamonnmcmanus** [comment]
I think this is working as intended. In your first error example, you are asking Gson to decode this JSON string:
```
{ "password": "p02-foo"bar" }
```
It needs to be this:
```
{ "password": "p02-foo\"bar" }
```
You could achieve that either by obtaining the string using `GSON.toJson(creds)` or by quoting the password manually with
```java
String quotedPassword = password.replace("\\", "\\\\").replace("\"", "\\\"")
```

**Comment by pjoe** [comment]
🤦You are right of course, thank you. Guessing the issue I see in the real app must happen before `fromJson`, either on the serialization side or the `\`s get decoded once before being fed to `fromJson`.

Anyway thanks for taking a look, will closing the issue.
