### ISSUE TITLE
Can't deserialise objects with certain type in

### ISSUE THREAD

**Issue by peepshow-21** [google/gson#2297]
# Gson version
2.10.1

# Java / Android version
Java 17

# Used tools
Any

# Description
Can't deserialise objects with certain types in (Color in this case), even if the type data is missing/NULL in the JSON.

## Expected behavior
Runs in Java 8 OK

## Actual behavior
This Exception in Java 17
```
Exception in thread "main" com.google.gson.JsonIOException: Failed making field 'java.awt.Color#value' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
```

# Reproduction steps
Simple Test Case
```

import com.google.gson.Gson;
import java.awt.Color;

public class GsonColor {
    
    public static void main(String[] args) {
        
        Gson gson = new Gson();
        Object obj = gson.fromJson(gson.toJson(new MyThing()), MyThing.class);
    }

    public static class MyThing {

        public int value;
        public Color color;

    }
}
```

# Exception stack trace
```
Exception in thread "main" com.google.gson.JsonIOException: Failed making field 'java.awt.Color#value' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.Gson.toJson(Gson.java:834)
	at com.google.gson.Gson.toJson(Gson.java:812)
	at com.google.gson.Gson.toJson(Gson.java:759)
	at com.google.gson.Gson.toJson(Gson.java:736)
	at misc.GsonColor.main(GsonColor.java:11)
```

**Comment by Marcono1234** [comment]
You are (implicitly) trying to use the reflection-based Gson adapter for the JDK class `java.awt.Color`. That adapter tries to access the internal fields of that JDK class, which is not allowed. To solve this you have to write a custom `TypeAdapter` for `Color`. See also the [troubleshooting guide](https://github.com/google/gson/blob/master/Troubleshooting.md#inaccessibleobjectexception-module--does-not-opens--to-unnamed-module) for a bit more information.

If you don't actually want that field of type `Color` in your class to be serialized or deserialized you can make it `transient`.
