### ISSUE TITLE
java.lang.StackOverflowError: null getDelegateAdapter

### ISSUE THREAD

**Issue by 371873574** [google/gson#2312]
# Gson version 2.8.5
# Java version 8
# Used tools kubernetes/client-java  version 13.0.1
# Description
java.lang.StackOverflowError: null
        at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:72)
        at com.google.gson.reflect.TypeToken.get(TypeToken.java:303)
        at io.kubernetes.client.util.generic.dynamic.DynamicKubernetesTypeAdaptorFactory.shouldHandleAsSingleObject(DynamicKubernetesTypeAdaptorFactory.java:41)
        at io.kubernetes.client.util.generic.dynamic.DynamicKubernetesTypeAdaptorFactory.create(DynamicKubernetesTypeAdaptorFactory.java:31)
        at com.google.gson.Gson.getDelegateAdapter(Gson.java:541)
        at io.kubernetes.client.util.generic.dynamic.DynamicKubernetesTypeAdaptorFactory.create(DynamicKubernetesTypeAdaptorFactory.java:37)
        at com.google.gson.Gson.getDelegateAdapter(Gson.java:541)
        at io.kubernetes.client.util.generic.dynamic.DynamicKubernetesTypeAdaptorFactory.create(DynamicKubernetesTypeAdaptorFactory.java:37)
        at com.google.gson.Gson.getDelegateAdapter(Gson.java:541)
        at io.kubernetes.client.util.generic.dynamic.DynamicKubernetesTypeAdaptorFactory.create(DynamicKubernetesTypeAdaptorFactory.java:37)
        at com.google.gson.Gson.getDelegateAdapter(Gson.java:541)
        at io.kubernetes.client.util.generic.dynamic.DynamicKubernetesTypeAdaptorFactory.create(DynamicKubernetesTypeAdaptorFactory.java:37)
        at com.google.gson.Gson.getDelegateAdapter(Gson.java:541)

**Comment by 371873574** [comment]
Thank you. DynamicKubernetesTypeAdaptorFactory has registered more than once. Is this sure to cause the above problems? Because StackOverflowError is an occasional problem, it is not easy to verify

**Comment by eamonnmcmanus** [comment]
FWIW, I proposed a fix in https://github.com/kubernetes-client/java/pull/2553.

**Comment by 371873574** [comment]
thank you！！！

**Comment by JoshuaLamley** [comment]
Joshua Stuart Lamley
