### ISSUE TITLE
Support of serdes for Throwable/Exception no longer works since Java 17

### ISSUE THREAD

**Issue by q3769** [google/gson#2352]
# Gson version

2.10.1

# Java / Android version

17.0.6 Amazon Corretto

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

```
    public static void main(String[] args) {
        System.out.println("11111111111111111111111111111111111111111 " + new Gson().toJson(new ExBean()));
    }

    static class ExBean {
        Throwable throwable = new Exception("xxxxxxxxxxxxxxxxx");
    }
```

## Expected behavior

Gson should serialize the ExBean instance with the Throwable field, with stack trace details and related info on the Exception.

## Actual behavior

Gson.toJson errors out with exception. See stack trace below.

# Reproduction steps

1. paste this in a class

```
    public static void main(String[] args) {
        System.out.println("11111111111111111111111111111111111111111 " + new Gson().toJson(new ExBean()));
    }

    static class ExBean {
        Throwable throwable = new Exception("xxxxxxxxxxxxxxxxx");
    }
```

2. Run the main method

# Exception stack trace

```
Exception in thread "main" com.google.gson.JsonIOException: Failed making field 'java.lang.Throwable#detailMessage' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.Gson.toJson(Gson.java:834)
	at com.google.gson.Gson.toJson(Gson.java:812)
	at com.google.gson.Gson.toJson(Gson.java:759)
	at com.google.gson.Gson.toJson(Gson.java:736)
	at elf4j.engine.writer.pattern.JsonPatternSegment.main(JsonPatternSegment.java:129)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @136432db
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35)
	... 12 more

```

**Comment by Marcono1234** [comment]
Have added the "enhancement" label because there was never really proper support for `Throwable`; it just accessed the internal fields of the JDK classes. And that was already flawed; if `Throwable.getStackTrace()` had not been called (indirectly) before the exception was passed to Gson, the JSON output would contain `"stackTrace":[]` because the stack trace had not been initialized yet. It also did not include the exception type, so if the exception message itself was not meaningful enough (e.g. `NullPointerException` might not have any message at all), you would have no clue what kind of exception occurred.

Backward compatibility might also be a (small) problem: If Gson added now a type adapter factory which handles `Throwable` and all subclasses, it would not include custom fields from subclasses anymore.

Most likely it is also not possible to properly support deserialization because exceptions can have arbitrary constructors (which might make adjustments to the provided message), so even if Gson was able to create an instance of an exception, the instance would most likely not be identical to the original one.

Note that I am not a direct member of this project, but my opinion is that users should write their own adapter, and include all information they consider important. Here is an example for including the type name, the message, the cause and suppressed exceptions:
```java
class ThrowableAdapterFactory implements TypeAdapterFactory {
  private ThrowableAdapterFactory() {}

  public static final ThrowableAdapterFactory INSTANCE = new ThrowableAdapterFactory();

  @Override
  public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    // Only handles Throwable and subclasses; let other factories handle any other type
    if (!Throwable.class.isAssignableFrom(type.getRawType())) {
      return null;
    }

    @SuppressWarnings("unchecked")
    TypeAdapter<T> adapter = (TypeAdapter<T>) new TypeAdapter<Throwable>() {
      @Override
      public Throwable read(JsonReader in) throws IOException {
        throw new UnsupportedOperationException();
      }

      @Override
      public void write(JsonWriter out, Throwable value) throws IOException {
        if (value == null) {
          out.nullValue();
          return;
        }

        out.beginObject();
        // Include exception type name to give more context; for example NullPointerException might
        // not have a message
        out.name("type");
        out.value(value.getClass().getSimpleName());

        out.name("message");
        out.value(value.getMessage());

        Throwable cause = value.getCause();
        if (cause != null) {
          out.name("cause");
          write(out, cause);
        }

        Throwable[] suppressedArray = value.getSuppressed();
        if (suppressedArray.length > 0) {
          out.name("suppressed");
          out.beginArray();

          for (Throwable suppressed : suppressedArray) {
            write(out, suppressed);
          }

          out.endArray();
        }
        out.endObject();
      }
    };
    return adapter;
  }
}
```

And then register it like this:
```java
new GsonBuilder()
  .registerTypeAdapterFactory(ThrowableAdapterFactory.INSTANCE)
  .create()
```

**Comment by Marcono1234** [comment]
> BTW, is there an easier (more relaxed) way to register user customized adapters? For example, the Adapter interface has both read and write methods but I see little reason to force the user to implement both if they only need either serialization or deserialization. Wouldn't being able to register serializer/writer and deserializer/reader separately more convenient?

There are the separate interfaces [`JsonSerializer`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonSerializer.html) and [`JsonDeserializer`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonDeserializer.html), and you could register them with [`GsonBuilder.registerTypeHierarchyAdapter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#registerTypeHierarchyAdapter(java.lang.Class,java.lang.Object)). However, as mentioned in the documentation of these interfaces they are less efficient than `TypeAdapter` because they work on a complete in-memory representation of the JSON data in the form of a `JsonElement` object. Additionally, compared to `TypeAdapterFactory` they don't support delegating to the built-in adapter for the same type, e.g. to perform pre-processing.

The easiest solution would probably be to implement `TypeAdapter` but let its `write` respectively `read` method unconditionally throw an exception.
