### ISSUE TITLE
TypeToken R8

### ISSUE THREAD

**Issue by lUjek-Sh** [google/gson#2380]
# Gson version
2.10.1

# Java / Android version
JDK 17

# Used tools

- [ ] Gradle; version:  8.0
- [ ] ProGuard (attach the configuration file please); version: Last

# Exception stack trace
```
java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
2023-05-01 14:44:07.853  W  	at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:100)
2023-05-01 14:44:07.853  W  	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:70)
```

**Comment by Marcono1234** [comment]
Can you please provide more information? In particular, please show your code which creates the `TypeToken` instance.

Additionally, have you configured the following ProGuard / R8 rules?
```
-keepattributes Signature
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
```
See also the [Gson Android ProGuard example](https://github.com/google/gson/tree/master/examples/android-proguard-example) and the [R8 FAQ](https://r8.googlesource.com/r8/+/refs/heads/main/compatibility-faq.md#troubleshooting-gson-gson).

**Comment by lUjek-Sh** [comment]
> 
I add ProGuard full rules from example but not help.

My code:
```
    private fun mapFromJson(jsonString: String): HashMap<String, Any> {
        val type = object : TypeToken<HashMap<String, Any>>() {}.type
        return Gson().fromJson(jsonString, type)
    }
```

**Comment by lUjek-Sh** [comment]
Sorry my problem.

I forgot to add when testing
`
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
`
