### ISSUE TITLE
Throw MalformedJsonException or JsonSyntaxException instead of IllegalStateException

### ISSUE THREAD

**Issue by vlsi** [google/gson#2457]
# Gson version

2.10.1

# Java / Android version

Java 11

# Used tools

- [ ] Maven; version: 
- [x] Gradle; version: 7.6
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

Fuzz tests in `sigstore-java` fail as follows:

See https://github.com/sigstore/sigstore-java/actions/runs/5731035660/job/15531080684#step:4:1000

## Expected behavior

`Gson.fromJson` documentation says it throws `JsonSyntaxException` if json is invalid.

## Actual behavior

`Gson.fromJson` throws `IllegalStateException`.

# Reproduction steps

Run fuzzer for `fromJson(String json, TypeToken<T> typeOfT)`

# Exception stack trace

```
== Java Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:1014)
	at dev.sigstore.rekor.client.RekorResponse.newRekorResponse(RekorResponse.java:59)
	at fuzzing.RekorTypesFuzzer.fuzzerTestOneInput(RekorTypesFuzzer.java:35)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:182)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 5 more
```

**Comment by vlsi** [comment]
Looks like the exception is already `JsonSyntaxException`. Sorry for the confusion.
