### ISSUE TITLE
Using gson to deserialize json in native image fails

### ISSUE THREAD

**Issue by sujun1992** [google/gson#2464]
# Gson version
2.10.1

# Java / Android version
17.0.8

# Used tools

# Description
I used gson in springboot, and the code works normally in normal mode. But I packaged the program into a native image and ran it, and an exception occurred.

## Actual behavior

# Reproduction steps

1. public record MicrosoftASRResponse(String RecognitionStatus, String DisplayText, String Offset,
                                   String Duration) {

}
2. Gson gson = new Gson()
3. var asrResponse = gson.fromJson(s, MicrosoftASRResponse.class);
4. my reflect-config.json  is 
5. ```[  {
    "name": "com.mobvoi.noise.microsoft.model.MicrosoftASRResponse",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredClasses": true,
    "unsafeAllocated": true
  }
]  ```

# Exception stack trace

```
2023-08-09 18:08:29.686 INFO  2800 --- [http-nio-8080-exec-3] com.mobvoi.noise.service.impl.NoiseServiceImpl - asr success {"RecognitionStatus":"Success","Offset":400000,"Duration":31600000,"DisplayText":"今天天气怎么样？"}
2023-08-09 18:08:29.686 ERROR 2800 --- [http-nio-8080-exec-3] com.mobvoi.noise.service.impl.NoiseServiceImpl - get issue token failed
java.lang.RuntimeException: Unexpected IllegalAccessException occurred (Gson 2.10.1). Certain ReflectionAccessFilter features require Java >= 9 to work correctly. If you are not using ReflectionAccessFilter, report this to the Gson maintainers.
        at com.google.gson.internal.reflect.ReflectionHelper.createExceptionForUnexpectedIllegalAccess(ReflectionHelper.java:153)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:399)
        at com.google.gson.Gson.fromJson(Gson.java:1227)
        at com.google.gson.Gson.fromJson(Gson.java:1137)
        at com.google.gson.Gson.fromJson(Gson.java:1047)
        at com.google.gson.Gson.fromJson(Gson.java:982)
        at com.mobvoi.noise.service.impl.NoiseServiceImpl.getAsr(NoiseServiceImpl.java:254)
        at com.mobvoi.noise.controller.NoiseController.asr(NoiseController.java:42)
        at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:179)
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field com.mobvoi.noise.microsoft.model.MicrosoftASRResponse.RecognitionStatus to java.lang.String
        at java.base@17.0.8/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
        at java.base@17.0.8/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
        at java.base@17.0.8/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
        at java.base@17.0.8/java.lang.reflect.Field.set(Field.java:799)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        ... 59 common frames omitted
```

**Comment by eamonnmcmanus** [comment]
It looks as if the native image transformation is somehow losing track of the fact that the class is a record? A couple of things you could try: in the app you could print these:
```java
System.out.printf("isClass: %s\n", MicrosoftASRResponse.class.isRecord());
System.out.printf("Gson isClass: %s\n", com.google.gson.internal.reflect.ReflectionHelper.isRecord(MicrosoftASRResponse.class));
```
I would expect both to print `true` in normal mode, but do they print `true` in the native image version?

**Comment by sujun1992** [comment]
in the native image,print this
`
2023-08-10 10:18:49.639 INFO  15464 --- [http-nio-8080-exec-2] com.mobvoi.noise.service.impl.NoiseServiceImpl - isClass: true
2023-08-10 10:18:49.639 INFO  15464 --- [http-nio-8080-exec-2] com.mobvoi.noise.service.impl.NoiseServiceImpl - Gson isClass: false
`

**Comment by eamonnmcmanus** [comment]
Thanks, that's very helpful!

I think the problem is [here](https://github.com/google/gson/blob/cdbbee4e723c39c1df302a805f3bde8d4fe12bd1/gson/src/main/java/com/google/gson/internal/reflect/ReflectionHelper.java#L219-L224):

```java
      isRecord = Class.class.getMethod("isRecord");
      getRecordComponents = Class.class.getMethod("getRecordComponents");
      // Class java.lang.reflect.RecordComponent
      Class<?> classRecordComponent = getRecordComponents.getReturnType().getComponentType();
      getName = classRecordComponent.getMethod("getName");
      getType = classRecordComponent.getMethod("getType");
```

This code uses reflection to access methods in `java.lang.Record` and `java.lang.reflect.RecordComponent`, so we don't have to maintain a different version of the code for JDK versions that do or do not have records. Based on the [documentation](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Reflection/), I think GraalVM's reflection support should be able to figure this out, _except_ for this line:

```java
      Class<?> classRecordComponent = getRecordComponents.getReturnType().getComponentType();
```

Probably if we changed that to this:

```java
    Class<?> classRecordComponent = Class.forName("java.lang.reflect.RecordComponent");
```

then everything would work.

Meanwhile, you should be able to use [manual configuration](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Reflection/#manual-configuration) to tell GraalVM to support this reflective access. I think it would be something like this in a `reflect-config.json` file:

```
[
  {
    "name": "java.lang.reflect.RecordComponent",
    "allPublicMethods": true
  }
]
```

**Comment by sujun1992** [comment]
It's working ,Thanks

**Comment by eamonnmcmanus** [comment]
Excellent news!

**Comment by joerg-wille** [comment]
@eamonnmcmanus Is this fix in any release version yet, if not, when will a new version be deployed to maven central?

**Comment by muhrifqii** [comment]
I'm not sure why it's not working on my side. I am on serializing list of record into json and get the following exception
```
java.lang.RuntimeException: Unexpected ReflectiveOperationException occurred (Gson 2.11.0). To support Java records, reflection is utilized to read out information about records. All these invocations happens after it is established that records exist in the JVM. This exception is unexpected behavior.
	at com.google.gson.internal.reflect.ReflectionHelper.createExceptionForRecordReflectionException(ReflectionHelper.java:210)
	at com.google.gson.internal.reflect.ReflectionHelper.access$300(ReflectionHelper.java:28)
	at com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper.getCanonicalRecordConstructor(ReflectionHelper.java:281)
	at com.google.gson.internal.reflect.ReflectionHelper.getCanonicalRecordConstructor(ReflectionHelper.java:195)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.<init>(ReflectiveTypeAdapterFactory.java:579)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:155)
	at com.google.gson.Gson.getAdapter(Gson.java:628)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:57)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:99)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:59)
	at com.google.gson.Gson.toJson(Gson.java:944)
	at com.google.gson.Gson.toJson(Gson.java:899)
	at com.google.gson.Gson.toJson(Gson.java:848)
	at com.google.gson.Gson.toJson(Gson.java:825)
	at com.muhrifqii.scrapper.serde.OutputWriterImpl.dumpToJson(OutputWriterImpl.java:23)
	at com.muhrifqii.scrapper.OpdbScrapApp.call(OpdbScrapApp.java:31)
	at com.muhrifqii.scrapper.OpdbScrapApp.call(OpdbScrapApp.java:16)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at com.muhrifqii.scrapper.OpdbScrapApp.main(OpdbScrapApp.java:46)
	at java.base@23/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base@23/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper.getCanonicalRecordConstructor(ReflectionHelper.java:272)
	... 24 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Record components not available for record class com.muhrifqii.scrapper.df.DevilFruitTypeInfo. All record component accessor methods of this record class must be included in the reflection configuration at image build time, then this method can be called.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:121)
	at java.base@23/java.lang.Class.getRecordComponents0(DynamicHub.java:1314)
	at java.base@23/java.lang.Class.getRecordComponents(DynamicHub.java:2666)
	... 26 more
```

**Comment by Marcono1234** [comment]
@muhrifqii, did you follow the advice given in the exception message above?
> Record components not available for record class com.muhrifqii.scrapper.df.DevilFruitTypeInfo. All record component accessor methods of this record class must be included in the reflection configuration at image build time, then this method can be called.

Here [is an example from Gson's integration tests](https://github.com/google/gson/blob/gson-parent-2.11.0/graal-native-image-test/src/test/resources/META-INF/native-image/reflect-config.json#L44-L49). However, in the latest GraalVM versions it seems there is now a single `reachability-metadata.json` file instead, see https://www.graalvm.org/latest/reference-manual/native-image/metadata/#specifying-metadata-with-json
