### ISSUE TITLE
Unicodes bug?

### ISSUE THREAD

**Issue by cooffeeRequired** [google/gson#2494]
# Gson version
2.10.1

# Java / Android version
Java 20

# Used tools
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\plugins\maven\lib\maven3
Java version: 17.0.8, vendor: JetBrains s.r.o., runtime: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\jbr
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
# Description

```
Basically I'm trying to use unicodes, although they are perfectly normal for JSON so Gson has a big problem with that.
```

## Expected behavior
return JsonElement `{"escape": "\u000"}`

## Actual behavior
Throw the error what i describe up. also they trying parse that as like number.

# Reproduction steps
```java
public class Test {
    public static void main(String[] args) throws Exception {
        String test = "{\"escape\": \"\\u000\"}"; // použijte \u0000 pro znak s hodnotou 0
        System.out.println(test);
        JsonElement json = JsonParser.parseString(test);
        System.out.println(json);
    }
}

```
# Exception stack trace
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: \u000"
	at com.google.gson.internal.Streams.parse(Streams.java:65)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:102)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:70)
	at com.google.gson.JsonParser.parseString(JsonParser.java:51)
	at cz.coffee.skjson.test.Test.main(Test.java:21)
Caused by: java.lang.NumberFormatException: \u000"
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1617)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1027)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
	at com.google.gson.internal.Streams.parse(Streams.java:49)
	... 4 more

```

**Comment by Marcono1234** [comment]
The Unicode escape `\u000` in your example only has three `0`s; however the [JSON specification](https://www.rfc-editor.org/rfc/rfc8259#section-7) requires that Unicode escapes always have four hex digits. Can you please try `\u0000`? Gson should be able to parse that without issues.

**Comment by eamonnmcmanus** [comment]
Closing as Not Planned. Feel free to reopen if there is something further to say.

**Comment by SkJsonTeam** [comment]
Hello there, tried with `\u0000` but i got `"\\u0000` it's that right?

**Comment by eamonnmcmanus** [comment]
> Hello there, tried with `\u0000` but i got `"\\u0000` it's that right?

I think we would need to see more detail. This looks fine to me, for example:
```
$ jshell -c ~/.m2/repository/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
|  Welcome to JShell -- Version 22
|  For an introduction type: /help intro

jshell> import com.google.gson.*

jshell> JsonParser.parseString("\"\\u0000\"")
$2 ==> "\u0000"

jshell> $2.getClass()
$3 ==> class com.google.gson.JsonPrimitive

jshell> $2.getAsString()
$4 ==> "\000"

jshell> $4.length()
$5 ==> 1
```
