### ISSUE TITLE
Can't read multiline string in JSON5

### ISSUE THREAD

**Issue by eitanborisov** [google/gson#2682]
# Gson version
2.11.0.

# Java / Android version
OpenJDK 17, 1.8 language level, Kotlin 1.9.20.

# Used tools
- [ ] No build tool, IntelliJ IDEA 2024.1 (Community Edition).

# Description
JSON5 specification supports multiline strings, like that:
```
'dialogue': "A: Hello!\
B: Hi!"
```
It's very convenient notation, so I can split the string into multiple lines, ant not to use `\n`.

But when I try to parse a file that contains such string, I get an exception.

## Expected behavior
The string should be read by the parser as a string.

## Actual behavior
I get next error: `Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line [DELETED] column [DELETED] path $.`

# Exception stack trace
```
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line [DELETED] column [DELETED] path $.
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.Gson.fromJson(Gson.java:1375)
	at com.google.gson.Gson.fromJson(Gson.java:1262)
	at com.google.gson.Gson.fromJson(Gson.java:1171)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.[DELETED]
	at com.[DELETED]
	at com.[DELETED]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line [DELETED] column [DELETED] path $.
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1754)
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1744)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1103)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:907)
	at com.google.gson.internal.bind.ObjectTypeAdapter.readTerminal(ObjectTypeAdapter.java:94)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:116)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:200)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:154)
	at com.google.gson.Gson.fromJson(Gson.java:1361)
	... 6 more
```

**Comment by Marcono1234** [comment]
Are you sure this is really a <code>&bsol;<i>LF</i></code>[^1] and not something else? Gson's `JsonReader` in lenient mode (which is the default for `Gson`) supports unescaped LF and <code>&bsol;<i>LF</i></code> in JSON string values. But it does no support for example <code>&bsol;<i>CR</i></code>.

This works without problems:
```java
String json = "{'dialogue': \"A: Hello!\\\nB: Hi!\"}";
System.out.println(new Gson().fromJson(json, Object.class));
```
This should be identical to your example (except that extra escaping is needed for the Java string literal).

Could you please provide a small reproducible code snippet which demonstrates the issue?

Note however that Gson's lenient mode is _not_ the same as JSON5; see the [`JsonReader#setStrictness` documentation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonReader.html#setStrictness(com.google.gson.Strictness)) for more details about Gson's lenient mode.

[^1]: _LF_ being the character which is represented by a `\n`.
And _CR_ being the character represented by `\r`.

**Comment by eitanborisov** [comment]
> Are you sure this is really a `\LF`[1](#user-content-fn-1-e444797267af408027bf16104ba57d0d) and not something else? Gson's `JsonReader` in lenient mode (which is the default for `Gson`) supports unescaped LF and `\LF` in JSON string values. But it does no support for example `\CR`.
> 
> This works without problems:
> 
> ```java
> String json = "{'dialogue': \"A: Hello!\\\nB: Hi!\"}";
> System.out.println(new Gson().fromJson(json, Object.class));
> ```

Thank you! It really works!

**Comment by Marcono1234** [comment]
Ok, thanks for letting us know! I am going to close this issue then.
