### ISSUE TITLE
TypeToken.getParameterized(Response.class, List.class, Long.class) get IllegalArgumentException: requires 1 type arguments, but got 2

### ISSUE THREAD

**Issue by hfxu** [google/gson#2703]
# Gson version
2.11.0

# Java / Android version
JDK17

# Used tools
Maven 

# Description
When upgrade gson from 2.8.9 to 2.11.0, the below code not working with gson-2.11.0:
`Type responseType = TypeToken.getParameterized(Response.class, List.class, Long.class).getType();`
And it's thrown a exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: GsonTest$Response requires 1 type arguments, but got 2
	at com.google.gson.reflect.TypeToken.getParameterized(TypeToken.java:402)
	at com.waffo.backend.common.utils.GsonTest.main(GsonTest.java:13)
```

## Expected behavior

Got a correct Type of Response<List<Long>>.

## Actual behavior

Throw a exception like `java.lang.IllegalArgumentException: GsonTest$Response requires 1 type arguments, but got 2`

# Reproduction steps

```java
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import lombok.Data;

import java.lang.reflect.Type;
import java.util.List;

public class GsonTest {
    public static void main(String[] args) {
        String response = "{\"code\":\"000000\",\"data\":[148]}";
        Type responseType = TypeToken.getParameterized(Response.class, List.class, Long.class).getType();
        //would got exception at below line.
        Response<List<Long>> respObj = new Gson().fromJson(response, responseType);
        assert respObj.getData() != null && respObj.getData().size() == 1;
    }

    @Data
    static class Response<T> {
        private String code;
        private T data;
    }
}
```

# Exception stack trace

```
Exception in thread "main" java.lang.IllegalArgumentException: GsonTest$Response requires 1 type arguments, but got 2
	at com.google.gson.reflect.TypeToken.getParameterized(TypeToken.java:402)
	at com.waffo.backend.common.utils.GsonTest.main(GsonTest.java:13)
```

**Comment by Marcono1234** [comment]
Or alternatively create an anonymous `TypeToken` subclass:
```java
var responseType = new TypeToken<Response<List<Long>>>() {};
```

This prevents such such malformed type issues already at compile time.

You can then also use the `T Gson.fromJson(..., TypeToken<T>)` overloads which were added in Gson 2.10. These are more type safe compared to the `Gson.fromJson(..., Type)` overloads.

**Comment by hfxu** [comment]
Hi @Marcono1234 @eamonnmcmanus 
Thank you for your suggestion!
 It appears that I had been used the incorrect method all along.
