### ISSUE TITLE
LinkedTreeMap cannot be cast to ****

### ISSUE THREAD

**Issue by Andrii-suncor** [google/gson#2736]
# Gson version
    implementation "com.google.code.gson:gson:2.11.0"

# Java / Android version
        kotlin_version = '1.9.25'
        minSdkVersion = 28
        targetSdkVersion = 34
        compileSdkVersion = 34
        gsonVersion = '2.11.0'

  repositories {
        google()
        mavenCentral()
    } 

# Used tools
 
gradle-8.7-bin.zip

Proguard conf
```
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { <fields>; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

# Needed to keep generic types and @Key annotations accessed via reflection
-keepattributes RuntimeVisibleAnnotations,AnnotationDefault

-keepclassmembers class * {
  @com.google.api.client.util.Key <fields>;
}

# Needed by google-http-client-android when linking against an older platform version
-dontwarn com.google.api.client.extensions.android.**

# Needed by google-api-client-android when linking against an older platform version
-dontwarn com.google.api.client.googleapis.extensions.android.**

# Needed by google-play-services when linking against an older platform version
-dontwarn com.google.android.gms.**

# com.google.client.util.IOUtils references java.nio.file.Files when on Java 7+
-dontnote java.nio.file.Files, java.nio.file.Path

# Suppress notes on LicensingServices
-dontnote **.ILicensingService

# Suppress warnings on sun.misc.Unsafe
-dontnote sun.misc.Unsafe
-dontwarn sun.misc.Unsafe
##---------------End: proguard configuration for Gson  ----------
```

# Description
Incorrect class after parse json. Without proguard all works correct 
 
## Expected behavior
Should be DynamicPageWlModel but we have a LinkedTreeMap

## Actual behavior
We have LinkedTreeMap but should be DynamicPageWlModel

# Reproduction steps
 val dynamicMsgPagesResponse =
                        Gson().fromJson(
                            jsonText,
                            DynamicResponse::class.java
                        )

# Exception stack trace
 ```
Logger$UncaughtExceptionHandler.uncaughtException in SourceFile:496 :: Uncaught Exception
                                                                                                    java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to *********.DynamicPageWlModel
                                                                                                    	at *********.ApiDynamicMessageWLModule$getMessage$2$1.onSuccess(SourceFile:47)
                                                                                                    	at com.worklight.wlclient.api.WLResourceRequest.handleOnSuccess(SourceFile:763)
                                                                                                    	at com.worklight.wlclient.api.WLResourceRequest.access$100(SourceFile:67)
                                                                                                    	at com.worklight.wlclient.api.WLResourceRequest$1.onResponse(SourceFile:644)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```
Code for call
```
val dynamicMsgPagesResponse =
                        Gson().fromJson(
                            jsonText,
                            DynamicResponse::class.java
                        )
                        
  Log.d(
                            "TAG",
                            "Dynamic Message response: " + dynamicMsgPagesResponse[0].sections?.get(
                                0
                            )?.javaClass?.simpleName
                        )
                        
```
Models
 ```
@Keep
class DynamicResponse : ArrayList<DynamicPageWlModel>()

@Keep
class DynamicPageWlModel(
    @SerializedName("page_name")
    val pageName: String?,
    val sections: List<DynamicMessageSection>? = null

)

@Keep
class DynamicMessageSection(
    @SerializedName("section_name")
    val sectionName: String?,
    val message: String?
)

```

**Comment by Andrii-suncor** [comment]
Solution
Update proguad rules to actual 

at this time is 
```
### Gson ProGuard and R8 rules which are relevant for all users
### This file is automatically recognized by ProGuard and R8, see https://developer.android.com/build/shrink-code#configuration-files
###
### IMPORTANT:
### - These rules are additive; don't include anything here which is not specific to Gson (such as completely
###   disabling obfuscation for all classes); the user would be unable to disable that then
### - These rules are not complete; users will most likely have to add additional rules for their specific
###   classes, for example to disable obfuscation for certain fields or to keep no-args constructors
###

# Keep generic signatures; needed for correct type resolution
-keepattributes Signature

# Keep Gson annotations
# Note: Cannot perform finer selection here to only cover Gson annotations, see also https://stackoverflow.com/q/47515093
-keepattributes RuntimeVisibleAnnotations,AnnotationDefault

### The following rules are needed for R8 in "full mode" which only adheres to `-keepattribtues` if
### the corresponding class or field is matches by a `-keep` rule as well, see
### https://r8.googlesource.com/r8/+/refs/heads/main/compatibility-faq.md#r8-full-mode

# Keep class TypeToken (respectively its generic signature) if present
-if class com.google.gson.reflect.TypeToken
-keep,allowobfuscation class com.google.gson.reflect.TypeToken

# Keep any (anonymous) classes extending TypeToken
-keep,allowobfuscation class * extends com.google.gson.reflect.TypeToken

# Keep classes with @JsonAdapter annotation
-keep,allowobfuscation,allowoptimization @com.google.gson.annotations.JsonAdapter class *

# Keep fields with any other Gson annotation
# Also allow obfuscation, assuming that users will additionally use @SerializedName or
# other means to preserve the field names
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.Expose <fields>;
  @com.google.gson.annotations.JsonAdapter <fields>;
  @com.google.gson.annotations.Since <fields>;
  @com.google.gson.annotations.Until <fields>;
}

# Keep no-args constructor of classes which can be used with @JsonAdapter
# By default their no-args constructor is invoked to create an adapter instance
-keepclassmembers class * extends com.google.gson.TypeAdapter {
  <init>();
}
-keepclassmembers class * implements com.google.gson.TypeAdapterFactory {
  <init>();
}
-keepclassmembers class * implements com.google.gson.JsonSerializer {
  <init>();
}
-keepclassmembers class * implements com.google.gson.JsonDeserializer {
  <init>();
}

# Keep fields annotated with @SerializedName for classes which are referenced.
# If classes with fields annotated with @SerializedName have a no-args
# constructor keep that as well. Based on
# https://issuetracker.google.com/issues/150189783#comment11.
# See also https://github.com/google/gson/pull/2420#discussion_r1241813541
# for a more detailed explanation.
-if class *
-keepclasseswithmembers,allowobfuscation class <1> {
  @com.google.gson.annotations.SerializedName <fields>;
}
-if class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
-keepclassmembers,allowobfuscation,allowoptimization class <1> {
  <init>();
}

```
