### ISSUE TITLE
No built-in type adapter for Iterable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#428]
```
What steps will reproduce the problem?
See the attached file.

What is the expected output?
[{"a":1},{"a":2}]
[{"a":1},{"a":2}]
[1, 2]
[1, 2]

What do you see instead?
[{"a":1},{"a":2}]
{}
[1, 2]
Exception in thread "main" java.lang.RuntimeException: Unable to invoke no-args 
constructor for java.lang.Iterable<com.ash2k.test1.App$A>. Register an 
InstanceCreator with Gson for this type may fix this problem.
    at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:166)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:163)
    at com.google.gson.Gson.fromJson(Gson.java:755)
    at com.google.gson.Gson.fromJson(Gson.java:721)
    at com.google.gson.Gson.fromJson(Gson.java:670)
    at com.ash2k.test1.App.main(App.java:31)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48)
    at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:163)
    ... 5 more
Caused by: java.lang.InstantiationException: java.lang.Iterable
    at sun.misc.Unsafe.allocateInstance(Native Method)
    ... 11 more

What version of the product are you using? On what operating system?
2.1 on Ubuntu 11.10 x64

```

Original issue reported on code.google.com by `Ash2kk@gmail.com` on 1 Apr 2012 at 7:38

Attachments:
- [App.java](https://storage.googleapis.com/google-code-attachments/google-gson/issue-428/comment-0/App.java)

**Comment by inder123** [comment]
Hi Folks.
What is the intended behavior here? Do you want us to pick a random sub-class of Iterable (such as List) and deserialize the collection into it?

**Comment by jlapolla** [comment]
@inder123 To answer your question: yes, absolutely.

From a user's perspective this is consistent with the rest of Gson. When I ask Gson to deserialize some JSON to a `List<Integer>`, I don't much care which specific implementation of the `List<Integer>` interface Gson chooses to produce. It could be a `LinkedList<Integer>` or an `ArrayList<Integer>`. But as long as it's something that implements `List<Integer>` (and it's reasonably performant) I'm happy, and my code works.

In this case, Gson does exactly what you suggested: it picks an appropriate subclass of `List<Integer>` for me. It would be great if it did the same for an `Iterable<Integer>` as well.

I haven't dug into the Gson source code, so forgive me if this is technically impossible for some reason. But, from an outsider's perspective, this seems totally feasible.

I know this is an older issue, but I'm still having to work around this issue in my current project. As @ear...@gmail.com pointed out in his fourth paragraph on 8 Nov 2012, the workaround requires me to iterate over my `Iterable<Integer>` one more time, which is less than ideal.

**Comment by jlapolla** [comment]
Come to think of it, I've never tried to **deserialize** to anything but a concrete implementation (e.g. `LinkedList<Integer>`). But I certainly have serialized an interface (e.g. `List<Integer>`) without specifying the underlying implementation. It would be nice to be able to serialize `Iterable<Integer>` as well.
