### ISSUE TITLE
new Gson() fails on appengine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#468]
```
What steps will reproduce the problem?
1. Somewhere in program call 
  Gson gson = new Gson();
2. Run this code (using servlet or unit test) on appengine.
3. Nb! this code works in dev server but fails when deoployed on appengine.

What is the expected output? What do you see instead?
 java.lang.VerifyError: Cannot inherit from final class
    at com.google.appengine.runtime.Request.process-aa8514ea8d01585f(Request.java)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)


What version of the product are you using? On what operating system?
Gson 2.2.2
Appengine Java SDK 1.6.0


Please provide any additional information below.
It worked with older version of Gson (1.7.1) and same Appengine SDK version 
(1.6.0).
```

Original issue reported on code.google.com by `aleksandr.bg` on 28 Aug 2012 at 10:28

**Comment by eamonnmcmanus** [comment]
Closing this ancient bug as obsolete. App Engine no longer does the kind of byte code rewriting that provoked problems like these.
