### ISSUE TITLE
Gson fails to parse simple map

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#501]
```
When parsing the following json with gson (using 2.2.2 from maven-central), 
gson (fromJson) throws an:

JsonSyntaxException: "duplicate key: null"

whereby the json is created by gson (toJson) itself.

Json:
{"appProperties":{"server.configuration.reset":"false","server.db.jndi":"testDB"
,"xml.basedata.list":"basedata.xml","server.configuration.cache":"false","xml.la
yout.list":"","server.rolemapper":"InsertionRoleMapper","xml.content.list":"data
.xml"}}

http://json.parser.online.fr/ validates the string as correct...
```

Original issue reported on code.google.com by `phil...@meisen.net` on 15 Feb 2013 at 12:04

**Comment by busylee999** [comment]
I faced the same trouble. But I figured out it was because of we have map<enum, T> and ones  server started returns new enum type, we had not had yet, so it leaded to this error, two nulls as keys.

**Comment by tylerjameshurst** [comment]
I'm serializing a map.. the json object only has one key in it, and it's throwing this exception. Not sure why.
Every call to the map's put is using putIfAbsent.
`"map": {
      "string_key": 0
    }`
`com.google.gson.JsonSyntaxException: duplicate key: string_key`

**Comment by TheDoctorOne** [comment]
Since issue is still open, i'm guessing its still here.  Here is how i solved my case: 
I had an issue with Map<enum, list> like everyone else. After seeing this issue and debugging realized it was because of the enum. 
So I cast my Map<enum, list> to Map<Integer, list>. Then did my serialization / de-serialization.

Here is an example code, similar to mine. Changed variable names etc.
```java
public static Map<Enum, List<String>> fromOrdinal(Map<Integer, List<String>> ordMap) {
    Map<Enum, List<String>> org = new HashMap<>();
    for(int ord : ordMap.keySet()) {
	    org.put(Enum.values()[ord], ordMap.get(ord));
    }
    return org;
}

public static Map<Integer, List<String>> toOrdinal(Map<Enum, List<String>> map) {
    Map<Integer, List<String>> ord = new HashMap<>();
    for(Enum key : map.keySet()) {
	    ord.put(key.ordinal(), map.get(key));
    }
    return ord;
}
```

**Comment by eamonnmcmanus** [comment]
I don't think there's enough information in this issue to be actionable. There may be more than one underlying issue, or there may be none and people are just not using the API right. (So there might be a documentation issue.)

If you have a problem that seems like this one, please show an exception backtrace and the code you are using to deserialize.

**Comment by TheDoctorOne** [comment]
> 
> 
> I don't think there's enough information in this issue to be actionable. There may be more than one underlying issue, or there may be none and people are just not using the API right. (So there might be a documentation issue.)
> 
> If you have a problem that seems like this one, please show an exception backtrace and the code you are using to deserialize.

Here is the exact code i am testing it right now:

```java
package net.mahmutkocas.dummy;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.util.*;

public class Main {

    public static void main(String[] args) {

        TestClass testClass = new TestClass();
        for(TestEnum s : TestEnum.values()) {
            testClass.typesMap.put(s, "test");
        }

        GsonBuilder builder = new GsonBuilder();
        Gson gson = builder.create();

        try {
            String json= gson.toJson(testClass);
            System.out.println(json); // Output is provided at below with backtrace.
            gson.fromJson(json, TestClass.class);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public enum TestEnum {
        ENUM1,
        ENUM2,
        ENUM3,
        ENUM4;

        @Override
        public String toString() {
            return super.toString().toLowerCase(Locale.ENGLISH);
        }
    }


    public static class TestClass {
        public Map<TestEnum, String> typesMap = new HashMap<>();
    }

}
```

And here is the backtrace:
```
Output of the system.out : {"typesMap":{"enum2":"test","enum4":"test","enum1":"test","enum3":"test"}}

com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.mahmutkocas.dummy.Main.main(Main.java:22)
```

Hope it helps.
Note: This only happens if and only if when Enum's toString() method gets overriden and returning value does not equal to original name.

**Comment by eamonnmcmanus** [comment]
Thanks @TheDoctorOne, that does look suspicious and we should look into it.

**Comment by TheDoctorOne** [comment]
> 
> 
> Thanks @TheDoctorOne, that does look suspicious and we should look into it.

See #1950 , as far as i tested, it works. And should have backwards compatibility.
