### ISSUE TITLE
StackOverflowError on Android L

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#597]
```
What steps will reproduce the problem?

09-15 10:32:35.738    8954-9424/com.xxx.yyy.staging D/Retrofit-Log﹕ ---- 
ERROR http://www.xxx.com:3001/api/user?action=login
09-15 10:32:36.317    8954-9424/com.xxx.yyy.staging D/Retrofit-Log﹕ 
java.lang.StackOverflowError: stack size 1056KB
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:549)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:542)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:549)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:542)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:549)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:542)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:549)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:542)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:549)
            at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:108)
            at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:542)
What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
1.6, 1.7.1, 2.2.4, 2.3, Android L preview

Please provide any additional information below.
I built my app with Gson and Retrofit, it worked on every other Android 
versions except L preview. I tried some Gson versions (1.6, 1.7.1, 2.2.4, 2.3), 
none of them worked.
```

Original issue reported on code.google.com by `regcolle...@gmail.com` on 15 Sep 2014 at 3:17

Attachments:
- [gson_sofe.log](https://storage.googleapis.com/google-code-attachments/google-gson/issue-597/comment-0/gson_sofe.log)

**Comment by juanchosaravia** [comment]
I'm having the same issue. Any news?

**Comment by hennroja** [comment]
Check all attributes of the class that you want so serialize. Use `transient` or     `@JsonIgnoreProperties(ignoreUnknown=true)` to ignore attribute that can cause loops or something that is potentially not serializable.

In my case the class had a Marker (GMaps).

**Comment by quiet324** [comment]
Same issue.

**Comment by Marcono1234** [comment]
> If I had to guess it was a bug in ART's handling of generics through reflection.

To me this also looks like a potential bug with certain Android versions. Based on the stack trace is looks as if a wildcard type had itself as upper bound; something like: `? extends ?` (where both `?` are the same type instance).
(Or somehow Gson created a malformed `WildcardTypeImpl`.)

Note that this issue here is specifically about a `StackOverflowError` whose stack trace contains `$Gson$Types$WildcardTypeImpl.<init>` and `$Gson$Types.canonicalize` repeatedly.

For `StackOverflowError`s with other stack traces, please check if you have any circular references and prevent them by making fields `transient`.
