### ISSUE TITLE
Duplicate key on parsing list of maps

### ISSUE THREAD

**Issue by vitaliyistomov** [google/gson#655]
Hello,

I am parsing a JSON below with GSON 2.3.1 (as far as I see) using Retrofit 1.9.0. I need to have something like 

``` java
List<Map<String, Object>> data
```

because the names of the fields in the response are not static. But when I do this, parsing is failing with "duplicate key: id" exception. If I define it as

``` java
List<ClassWithAllFieldsStaticlyDefinedAsProperties> data
```

it works fine!

Is it an expected behaviour? Am I missing something here? Thanks for help!

Stacktrace:

``` stacktrace
 Caused by: com.google.gson.JsonSyntaxException: duplicate key: id
            at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190)
            at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
            at com.google.gson.Gson.fromJson(Gson.java:810)
            at com.google.gson.Gson.fromJson(Gson.java:775)
            at retrofit.converter.GsonConverter.fromBody(GsonConverter.java:63)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:367)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
```

JSON sample:

``` json
{
    "data": [
        {
            "id": 100,
            "displayName": "display name 0",
            "firstName": "first name 0",
            "some_property": 200,
            "lastName": "last name 0"
        },
        {
            "id": 101,
            "displayName": "display name 1",
            "firstName": "first name 1",
            "some_property": 201,
            "lastName": "last name 1"
        },
        {
            "id": 102,
            "displayName": "display name 2",
            "firstName": "first name 2",
            "some_property": 202,
            "lastName": "last name 2"
        }
    ],
    "internalErrorType": "GenericError",
    "internalErrorCode": 0,
    "errorLevel": 0,
    "errorMessage": "",
    "errorMessages": []
}
```

**Comment by swankjesse** [comment]
Are you sure your JSON doesn't include a repeated `id` field somewhere? A test case would be nice.

**Comment by vitaliyistomov** [comment]
The JSON sample from the first message is the one, I am trying to parse. I have renamed some sensitive fields and values, but there were no ```id``` among them. I have double checked it again.

**Comment by RoxRicardo** [comment]
I tried to simulate this error, but I did not have success.
I used the implementations ArrayList and HashMap.
```java
List<Map<String, Object>> list = new ArrayList<>();
		
		Map<String, Object> itemOne = new HashMap<>();
		itemOne.put("id", 100);
		itemOne.put("displayName", "display name 0");
		itemOne.put("firstName", "first name 0");
		itemOne.put("some_property", 200);
		itemOne.put("lastName", "last name 0");
		
		Map<String, Object> itemTwo = new HashMap<>();
		itemTwo.put("id", 101);
		itemTwo.put("displayName", "display name 1");
		itemTwo.put("firstName", "first name 1");
		itemTwo.put("some_property", 201);
		itemTwo.put("lastName", "last name 1");
		
		Map<String, Object> itemThree = new HashMap<>();
		itemThree.put("id", 102);
		itemThree.put("displayNme", "display name 2");
		itemThree.put("firstName", "first name 2");
		itemThree.put("some_property", 202);
		itemThree.put("lastName", "last name 2");
		
		list.add(itemOne);
		list.add(itemTwo);
		list.add(itemThree);
		
		Gson gson = new Gson();
		String result = gson.toJson(list);
```
Can you share your code with us?

**Comment by nafiux** [comment]
It works perfectly from Object to JSON, but fails from JSON to Object. I've the same problem, I'm trying to debug

**Comment by nafiux** [comment]
I have a pull request that fixed my problem:

https://github.com/google/gson/pull/997

**Comment by Marcono1234** [comment]
@vitaliyistomov, in case this is still relevant, could you please try the latest Gson version and provide a small self-contained example? Since you mentioned `List<Map<...>>` I am not sure if this is really the same `MultiValueMap` issue which @iocampomx was encountering.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
