### ISSUE TITLE
fromJson Json to String  JsonSyntaxException

### ISSUE THREAD

**Issue by KBCode** [google/gson#686]
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 13 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:786)
	at com.google.gson.Gson.fromJson(Gson.java:776)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.inspeed.commons.tools.GsonTools.fromJson(GsonTools.java:19)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 13 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1424)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:547)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:782)
	... 27 more

test code below
String timeStr=GsonTools.fromJson("2015-08-14 10:30:20",String.class);

 my view the source code of the STRING TypeAdapter is called found JsonReader nextString ( ) go to nextUnquotedValue() This method is positioned to see the case' ' : Will break, why?

if Use JsonReader.setLenient(true)  the result is 2015-08-14,This is not the result I want.

my expect value is '2015-08-14 10:30:20'

**Comment by JakeWharton** [comment]
`2015-08-14 10:30:20` is not a JSON string. You want `"2015-08-14 10:30:20"` (note the quotes). In JSON the space character is a delimiter for a token which is why it stops.

**Comment by ildar2** [comment]
@JakeWharton Should we disable GsonConverterFactory for requests that return Strings with colons or should we create a special deserializer for String return type?
