### ISSUE TITLE
Using Gson to convert jboss-cli responses.

### ISSUE THREAD

**Issue by vgtworld** [google/gson#720]
Currently I'm working on some kind of wrapper for jboss-cli that will allow me to easily execute commands in gui. For converting jboss-cli output I'm using Gson and despite output not being properly formatted json it's working perfectly for me with simple outputs. For example:

```
{
    "outcome" => "success",
    "result" => {
        "user.dir" => "/home/vgt/java/bin/jboss/wildfly-9.0.1.Final/bin",
        "user.home" => "/home/vgt",
        "user.language" => "en",
        "user.name" => "vgt",
        "user.timezone" => "Europe/Warsaw"
    }
}
```

Is correctly mapped to this class:

``` Java
public class TestResponse {

    private String outcome;

    private Map<String, String> result;

    //getters & setters
}
```

I don't know if conversion from this format working is pure luck and it's not supported, or it's intended to handle this format. But if it's the latter, I have more complex output from jboss-cli that is failing:

```
{
    "outcome" => "success",
    "result" => [
        {
            "address" => [
                ("subsystem" => "logging"),
                ("logger" => "org.jboss.security")
            ],
            "outcome" => "success",
            "result" => {
                "category" => "org.jboss.security",
                "filter" => undefined,
                "filter-spec" => undefined,
                "handlers" => undefined,
                "level" => "TRACE",
                "use-parent-handlers" => true
            }
        },
        {
            "address" => [
                ("subsystem" => "logging"),
                ("logger" => "com.example")
            ],
            "outcome" => "success",
            "result" => {
                "category" => "com.example",
                "filter" => undefined,
                "filter-spec" => undefined,
                "handlers" => undefined,
                "level" => "TRACE",
                "use-parent-handlers" => true
            }
        }
    ]
}
```

Here the problem is "address" element. Gson is unable to convert it and during parsing it throws an exception: **JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING**

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 6 column 17 path $.result[0].address[0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
    at com.google.gson.Gson.fromJson(Gson.java:814)
    at com.google.gson.Gson.fromJson(Gson.java:779)
    at com.google.gson.Gson.fromJson(Gson.java:728)
    at com.google.gson.Gson.fromJson(Gson.java:700)
    at pl.vgtworld.wildflyui.connector.translators.GenericGsonTranslatorTest.shouldSuccessfullyTranslateLoggersListResponse(GenericGsonTranslatorTest.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 6 column 17 path $.result[0].address[0]
    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
    ... 36 more
```

So my question here is: does Gson should even handle this kind of output successfully and if yes, can I get it to work with complex example I showed?

Gson version used: 2.4

**Comment by toddiuszho** [comment]
I think the parentheses in the address blocks are killing it. Try stripping those out.

**Comment by sibennayak** [comment]
private Map<String, Object> result;

**Comment by Marcono1234** [comment]
Parsing mostly worked because Gson is [lenient](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonReader.html#setLenient(boolean)) by default. However, it would probably be better to write a custom parser for your data (or search if someone else has already done it).

**Comment by eamonnmcmanus** [comment]
This bug is nearly 7 years old and I am closing it as obsolete.
