### ISSUE TITLE
json conversion error in retrofit 2

### ISSUE THREAD

**Issue by abhishekgargg** [google/gson#779]
I am facing problem in fetching json data from a GET request using retrofit.
Below is the stack trace to the problem. How do I get rid of this error?

java.io.EOFException: End of input at line 1 column 1
                                                                                           at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1414)
                                                                                           at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:553)
                                                                                           at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
                                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:202)
                                                                                           at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
                                                                                           at retrofit2.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:33)
                                                                                           at retrofit2.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:23)
                                                                                           at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:154)
                                                                                           at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:92)
                                                                                           at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                                           at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by abhishekgargg** [comment]
I am using these libraries..
compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'

**Comment by JakeWharton** [comment]
This happens because you told Gson to deserialize data from a stream into some object and the stream is empty. If there is no data, Gson should not be called (and you can return null or however you want to indicate to the calling code that there's no data).
