### ISSUE TITLE
Exception on Android M

### ISSUE THREAD

**Issue by srinivas3120** [google/gson#887]
java.lang.SecurityException: Can't make field constructor accessible
                                                                       at java.lang.reflect.Constructor.setAccessible(Constructor.java:334)
                                                                       at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:97)
                                                                       at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:79)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:71)
                                                                       at com.google.gson.Gson.getAdapter(Gson.java:356)
                                                                       at com.google.gson.internal.bind.MapTypeAdapterFactory.getKeyAdapter(MapTypeAdapterFactory.java:140)
                                                                       at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:125)
                                                                       at com.google.gson.Gson.getAdapter(Gson.java:356)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
                                                                       at com.google.gson.Gson.getAdapter(Gson.java:356)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
                                                                       at com.google.gson.Gson.getAdapter(Gson.java:356)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
                                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
                                                                       at com.google.gson.Gson.getAdapter(Gson.java:356)
                                                                       at com.google.gson.Gson.toJson(Gson.java:585)
                                                                       at com.google.gson.Gson.toJson(Gson.java:572)
                                                                       at com.google.gson.Gson.toJson(Gson.java:527)
                                                                       at com.google.gson.Gson.toJson(Gson.java:507)

**Comment by gastoncesarf** [comment]
Maybe #648 will be useful.

**Comment by JakeWharton** [comment]
Your model contains a `java.lang.reflect.Field` which is not a serializable type. Mark it as `transient` or exclude it from serialization using other means.
