### ISSUE TITLE
ISO8601 date parse exception with no 'Z' specified

### ISSUE THREAD

**Issue by ismoli** [google/gson#923]
GSON version 2.7

According to ISO8601 standard, "2016-09-06T15:30:00" is a valid date (No 'Z' means local time), however we get exception trying to parse it: 

```
Caused by: java.text.ParseException: 
Failed to parse date ["2016-09-06T15:30:00']: No time zone indicator (at offset 0)  
at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:274)
at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:72)
```

Is GSON ISO8601 date implementations support only a subset of specification?

**Comment by swankjesse** [comment]
Gson attempts to support RFC 3339.

**Comment by mcanyucel** [comment]
This issue is still valid.

**Comment by lepirlouit** [comment]
What is the workaround for this issue if you can't change the data provider ?

**Comment by shanyuliang** [comment]
I believe you can use a custom date deserializer in that case. Just use simpledateformat with "yyyy-MM-dd'T'hh:mm:ss" format.

**Comment by joeywp** [comment]
I believe that if you're using Joda-Time you can also use `DateTime("2016-09-06T15:30:00")` in a custom date type parser so you eventually get something like this (in Kotlin):

`class DateTypeAdapter : JsonDeserializer<Date> {
    override fun deserialize(json: JsonElement, typeOfT: Type, context: JsonDeserializationContext): Date {
        try {
            return DateTime(json.asString).toDate()
        } catch (e: Exception) {
            throw JsonParseException("'$json' is not a valid Date")
        }
    }
}`

As far as I know this is a little more flexible than just using ""yyyy-MM-dd'T'hh:mm:ss" in a SimpleDateFormat because Joda-Time follows the ISO1806 standard, without Joda-Time I guess this would be a good alternative though
