### ISSUE TITLE
[Crash] IncompatibleClassChangeError: Couldn't find com.google.b.a.c.a

### ISSUE THREAD

**Issue by feludens** [google/gson#974]
My application got some crashes because of this. 
Similarly to other IncompatibleClassChangeError, it only happens to Samsung devices (Os 5 and 6).

Does anybody know what causes this and how it should be fixed?

Here's the stack trace:

```
Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find com.google.b.a.c.a
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Field.getAnnotation(Field.java:242)
       at com.google.b.b.a.q.a(ReflectiveTypeAdapterFactory.java:72)
       at com.google.b.b.a.q.a(ReflectiveTypeAdapterFactory.java:159)
       at com.google.b.b.a.q.a(ReflectiveTypeAdapterFactory.java:100)
       at com.google.b.k.a(Gson.java:423)
       at com.google.b.k.a(Gson.java:886)
       at com.google.b.k.a(Gson.java:852)
       at com.google.b.k.a(Gson.java:801)
       at com.google.b.k.a(Gson.java:773)
       at com.mypackage.android.sdk.core.setup.ConfigurationAPI.loadApplicationConfiguration(ConfigurationAPI.java:62)
       at com.mypackage.android.sdk.core.setup.ConfigurationManager.loadApplicationConfiguration(ConfigurationManager.java:58)
       at com.mypackage.loader.ConfigurationLoadTask.executeTask(ConfigurationLoadTask.java:39)
       at com.mypackage.loader.ApplicationLoaderTask.run(ApplicationLoaderTask.java:28)
       at com.mypackage.loader.ApplicationLoader.setup(ApplicationLoader.java:42)
       at com.mypackage.loader.ApplicationLoaderService.onHandleIntent(ApplicationLoaderService.java:74)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Thanks

**Comment by JakeWharton** [comment]
This is likely due to ProGuard and your configuration of ProGuard in your build. It is not a problem with Gson itself and thus unsuited for this issue tracker which is only for Gson bugs and feature requests. Perhaps try StackOverflow?
